### ISSUE TITLE
Android bugs from Play Store and Countly

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1250]
Apparently the play store has a sort of travis to run tests and ui tests, 
in the last release we have 1 error, 25 warnings and 203 minor issues:

![Screenshot 2020-09-25 at 15.44.27.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/42857249-4a2e-4973-9ac6-cb65b8091917)

In this issue I want to focus to solve the crash and check out all the warnings and their impact

**Comment by lorenzoPrimi** [comment]
Update 1: The "Crash" is something we fixed it some time ago and only happened in a Android 5.0 version (that I'm not sure is supported or we are going to cut soon)

**Comment by lorenzoPrimi** [comment]
Update 2: The "warnings" are OS related warnings, no impact on crashes or to the actual user

**Comment by lorenzoPrimi** [comment]
Update 3: The minor issues are UI glitch we might evaluate together in a later time
![Screenshot 2020-09-28 at 10.22.19.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/c696c9ca-c6f2-4cd4-8383-1a0e11175523)

**Comment by lorenzoPrimi** [comment]
So far the only important thing to fix seem to be the crash identified in countly 
```
1
2
3
4
5
6
7
8
9
10
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
at org.openobservatory.ooniprobe.activity.MainActivity.onConfirmation(MainActivity.java:147)
at localhost.toolkit.app.fragment.ConfirmDialogFragment$1.onClick(ConfirmDialogFragment.java:44)
at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6864)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by bassosimone** [comment]
@lorenzoPrimi we support from KitKat (i.e. API level 19) onwards

**Comment by lorenzoPrimi** [comment]
https://github.com/ooni/probe-android/pull/368
will fix 
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference`
