### ISSUE TITLE
Crash on site check if connecting via NetGuard

### ISSUE THREAD

**Issue by licaon-kter** [ooni/probe#1303]
2.7.0, F-Droid, Android 10

With [NetGuard](https://github.com/M66B/NetGuard) 2.289 (local build) enabled for this app, app **allowed** to connect:
```
E Go      : panic: runtime error: invalid memory address or nil pointer dereference
E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x73a96643e8]
E Go      : 
E Go      : goroutine 17 [running, locked to thread]:
E Go      : github.com/ooni/probe-engine/oonimkall.(*Session).Geolocate(0x4000526150, 0x400000e080, 0x0, 0x0, 0x0)
E Go      :      /Users/runner/work/probe-engine/probe-engine/oonimkall/session.go:218 +0xa8
E Go      : main.proxyoonimkall_Session_Geolocate(0xffffffe5ffffffe7, 0x400007c058)
E Go      :      /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gomobile-work-858741544/src/gobind/go_oonimkallmain.go:111 +0x70
E Go      : main._cgoexpwrap_9d2d72aa2804_proxyoonimkall_Session_Geolocate(0xffffffe5ffffffe7, 0x73aeb07842)
E Go      :      _cgo_gotypes.go:372 +0x28
F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 25663 (AsyncTask ooni/probe-android#1), pid 25548 (atory.ooniprobe)
E ANDR-PERF-LM: VmRssMeter:: start() 298: Could not find pid, can not collect vmrss data
E ANDR-PERF-LM: AdaptiveLaunch: writeToDataBase() 63: Meter aborted or could not get meter data for this run
E cutils-trace: Error opening trace file: No such file or directory (2)
I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
I /system/bin/tombstoned: received crash request for pid 25663
I crash_dump64: performing dump of process 25548 (target tid = 25663)
F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F DEBUG   : Build fingerprint: 'google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys'
F DEBUG   : Revision: '0'
F DEBUG   : ABI: 'arm64'
F DEBUG   : Timestamp: 2020-10-18 20:50:57+0300
F DEBUG   : pid: 25548, tid: 25663, name: AsyncTask ooni/probe-android#1  >>> org.openobservatory.ooniprobe <<<
F DEBUG   : uid: 10256
F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
F DEBUG   :     x0  0000000000000000  x1  000000000000643f  x2  0000000000000006  x3  0000000000000008
F DEBUG   :     x4  0000000000000001  x5  0000000000000000  x6  000000000000000a  x7  0000000000000002
F DEBUG   :     x8  0000000000000083  x9  0000000000000003  x10 0000000000000000  x11 00000073a9b228d8
F DEBUG   :     x12 0000000000000000  x13 0000000000000000  x14 0000000000000000  x15 0000000000000001
F DEBUG   :     x16 00000073a8f0ddc3  x17 00000073a8f0ddc0  x18 00000073b827c000  x19 00000000000063cc
F DEBUG   :     x20 00000074048f15e0  x21 0000004000054000  x22 0000000000000000  x23 0000000000000000
F DEBUG   :     x24 0000004000522b40  x25 0000000000000000  x26 0000000000000000  x27 0000000000000010
F DEBUG   :     x28 0000004000000600  x29 00000074048f1ed0
F DEBUG   :     sp  0000004000163bb0  lr  00000073a8ef5e50  pc  00000073a8f0eb28
F DEBUG   : 
F DEBUG   : backtrace:
F DEBUG   :       #00 pc 0000000000549b28  /data/app/org.openobservatory.ooniprobe-jjO7GQqODcslqLk9sup-XA==/lib/arm64/libgojni.so
```

**All the other tests (IM, avoidance, perf) work fine.**

But, if I uncheck apply rules in NetGuard (aka bypass NetGuard), then the site check suddenly works fine.

I can repro at will.

I'll share the exact NetGuard settings if needed, there's basically Filtering ON, 2 DNS servers, Block hosts and other stuff.

@M66B Thoughts?

**Comment by bassosimone** [comment]
We have been testing a fix for this for a couple of weeks now. There was an unrelated use case where we did experience some issues that really look like this one. I believe we should take a look at this issue again near the end of January.

**Comment by bassosimone** [comment]
Both @lorenzoPrimi and I tested https://github.com/ooni/probe-android/pull/410, which fixes the original problem for us. Thank you for reporting this bug and providing us with a test case, @licaon-kter! This fix will be part of the next app release!

**Comment by bassosimone** [comment]
BTW, for the records, why did https://github.com/ooni/probe-android/pull/410 fixed the issue? I am not sure of the real reason regarding 2.7.0, because I didn't test that. I could test 2.9.1, where we were crashing at https://github.com/ooni/probe-engine/blob/v0.18.0/geolocate/resolverlookup.go#L31. I knew I refactored that part of the codebase recently in https://github.com/ooni/probe-engine/pull/1185/files#diff-abb70929303d17308c578b48e52b006604bb9512c6b938edb408d8d18beea9b4. I was not convinced by the original code (the error checking logic looked wrong) and so I rewrote it. Using https://github.com/ooni/probe-android/pull/410 fixed the issue because it included such a fix.
