### ISSUE TITLE
legacy, MK cannot measure https://1.1.1.1/dns-query

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1314]
When doing research on blocking of https://1.1.1.1/dns-query, I noticed that the legacy probe and MK based probes are not able to successfully measure this URL as well as any other URL where the input is an IP address.

This is what happens when running the legacy probe locally:

<details>
```
$ ooniprobe -P https web_connectivity -u https://1.1.1.1/dns-query
Looking up collector and test helpers with https://bouncer.ooni.io
Setting collector and test helpers for web_connectivity
Creating report with OONIB Reporter. Please be patient.
This may take up to 1-2 minutes...

Starting test for https://1.1.1.1/dns-query
* doing DNS query for 1.1.1.1
* doing HTTP(s) request https://1.1.1.1/dns-query
Error during info_callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 415, in dataReceived
    self._checkHandshakeStatus()
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 335, in _checkHandshakeStatus
    self._tlsConnection.do_handshake()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1425, in do_handshake
    result = _lib.SSL_do_handshake(self._ssl)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 917, in wrapper
    callback(Connection._reverse_mapping[ssl], where, return_code)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1151, in infoCallback
    return wrapped(connection, where, ret)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1250, in _identityVerifyingInfoCallback
    verifyHostname(connection, self._hostnameASCII)
  File "/usr/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 45, in verify_hostname
    obligatory_ids=[DNS_ID(hostname)],
  File "/usr/lib/python2.7/dist-packages/service_identity/_common.py", line 245, in __init__
    raise ValueError("Invalid DNS-ID.")
exceptions.ValueError: Invalid DNS-ID.

Error performing HTTP request: https://1.1.1.1/dns-query
Error during info_callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 415, in dataReceived
    self._checkHandshakeStatus()
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 335, in _checkHandshakeStatus
    self._tlsConnection.do_handshake()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1425, in do_handshake
    result = _lib.SSL_do_handshake(self._ssl)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 917, in wrapper
    callback(Connection._reverse_mapping[ssl], where, return_code)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1151, in infoCallback
    return wrapped(connection, where, ret)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1250, in _identityVerifyingInfoCallback
    verifyHostname(connection, self._hostnameASCII)
  File "/usr/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 45, in verify_hostname
    obligatory_ids=[DNS_ID(hostname)],
  File "/usr/lib/python2.7/dist-packages/service_identity/_common.py", line 245, in __init__
    raise ValueError("Invalid DNS-ID.")
exceptions.ValueError: Invalid DNS-ID.

Error performing HTTP request: https://1.1.1.1/dns-query
Error during info_callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 415, in dataReceived
    self._checkHandshakeStatus()
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 335, in _checkHandshakeStatus
    self._tlsConnection.do_handshake()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1425, in do_handshake
    result = _lib.SSL_do_handshake(self._ssl)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 917, in wrapper
    callback(Connection._reverse_mapping[ssl], where, return_code)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1151, in infoCallback
    return wrapped(connection, where, ret)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1250, in _identityVerifyingInfoCallback
    verifyHostname(connection, self._hostnameASCII)
  File "/usr/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 45, in verify_hostname
    obligatory_ids=[DNS_ID(hostname)],
  File "/usr/lib/python2.7/dist-packages/service_identity/_common.py", line 245, in __init__
    raise ValueError("Invalid DNS-ID.")
exceptions.ValueError: Invalid DNS-ID.

Error performing HTTP request: https://1.1.1.1/dns-query
Failed to perform HTTP request response_never_received
* performing control request with backend

Result for https://1.1.1.1/dns-query
------------------------------------
* No blocking detected
* Is NOT accessible

Status
------
1 completed 1 remaining
99.0% (ETA: 1s)
Summary for web_connectivity
----------------------------

Not accessible URLS
-------------------
* https://1.1.1.1/dns-query
Report ID: 20201218T135422Z_webconnectivity_IT_30722_n1_bYOlg7oeREUnNIXm
</details>

What is interesting is that a report is submitted and [published](https://explorer.ooni.org/measurement/20201218T135422Z_webconnectivity_IT_30722_n1_bYOlg7oeREUnNIXm?input=https%3A%2F%2F1.1.1.1%2Fdns-query) on OONI Explorer. Here the measurement is marked as if the website is down, but I have seen [other cases](https://explorer.ooni.org/measurement/20201218T055500Z_webconnectivity_RU_39289_n1_ykZVJ26ZDRMmh0uu?input=https%3A%2F%2F1.1.1.1%2Fdns-query%3Fdns%3Dq80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB) where the measurement is marked as an anomaly, which sadly is wrong.

This is what happens when running MK:

<details>
```
% measurement_kit --geoip-country-path country.mmdb --geoip-asn-path asn.mmdb web_connectivity -u https://1.1.1.1/dns-query
Contacting bouncer: https://bouncer.ooni.io
Using discovered collector: https://ams-pg.ooni.org:443
Bouncer discovered helper for web-connectivity: https://wcth.ooni.io
* Closing connection 0
Your country: IT
Your ISP identifier: AS30722
Your ISP name: Vodafone Italia S.p.A.
5%: geoip lookup
Results collector: https://ams-pg.ooni.org:443
Opening report; please be patient...
Report ID: 20201218T143948Z_webconnectivity_IT_30722_n1_MOwIIjUCthaNvZl9
10%: starting the test
10%: Processing input: https://1.1.1.1/dns-query
web_connectivity: starting dns_query for 1.1.1.1
web_connectivity: starting tcp_connect
web_connectivity: success to connect to 1.1.1.1:443
web_connectivity: starting http_request to https://1.1.1.1/dns-query
[!] web_connectivity: http-request error: ssl_error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
web_connectivity: doing control request
Using backend https://wcth.ooni.io
web_connectivity: comparing control with experiment
web_connectivity: no blocking detected
Submitting test results; please be patient...
Results successfully submitted
95%: ending the test
Closing report; please be patient...
Report successfully closed
100%: test complete
Overall data usage (bytes): 2527 down - 3631 up
```
</details>

The [corresponding measurement](https://explorer.ooni.org/measurement/20201218T143948Z_webconnectivity_IT_30722_n1_MOwIIjUCthaNvZl9?input=https%3A%2F%2F1.1.1.1%2Fdns-query) is (surprisingly to me) flagged as OK, but looking into it we see that there is a failure in handling the certificate, which means in other contexts this measurement could easily be flagged as anomaly.

We discussed this matter with @FedericoCeratto, and we concluded the best course of action is to flag this measurement as failed in the fastpath when processing or reprocessing the measurement.

**Comment by hellais** [comment]
This is blocking on the fact that we don't have a new test helper that uses probe-cli.

**Comment by hellais** [comment]
This is also related: https://github.com/ooni/probe-engine/issues/1046
