### ISSUE TITLE
probe-desktop: error after start

### ISSUE THREAD

**Issue by xhdix** [ooni/probe#1318]
It seems due to the failure to check for updates!
Probe-Desktop v3.0.1
Windows 10
TCI ;)

```
Unhandled Promise Rejection
Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
```

```

(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
12:29:01.792 > App starting...
12:29:01.880 > Checking for update
12:29:01.914 > Checking for update
(node:13960) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:13960) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
12:29:32.604 > Error: Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
12:29:32.659 > Error in auto-updater. Error: net::ERR_CONNECTION_CLOSED
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
(node:2616) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:2616) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
```

![image](https://user-images.githubusercontent.com/12384263/86920731-dc7e1f00-c132-11ea-955e-3057e6e70d1e.png)

![image](https://user-images.githubusercontent.com/12384263/86920466-84471d00-c132-11ea-8ee6-8cf279e6efad.png)

**Comment by sarathms** [comment]
This should be addressed by adding a `autoUpdater.on('error', handleFn)` in `main/index.js`. Thanks for reporting this @xhdix. I will make sure this is fixed in the next release.

**Comment by xhdix** [comment]
You're welcome @sarathms !
Now, months after this report, it seems that at TCI (AS58224) they are detecting and blocking ElectronJS JA3. (This doesn't happen in MCI (AS197207).

**Comment by sarathms** [comment]
As a longer term solution to this issue, we will be changing the auto-update provider to use something that is more resilient. This work is tracked in #1496

**Comment by sarathms** [comment]
For the short term, we now check for updates differently and are able to catch these errors and notify the unavailability of updates and request visiting our website to fetch the latest version.

**Comment by sarathms** [comment]
Closing this issue for now. Thanks @xhdix for your time and patience.
