### ISSUE TITLE
ci: wcth.ooni.io: dns_nxdomain_error

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1409]
```
-- FAIL: TestSmoke (1.60s)
panic: client.Do failed: Post "https://wcth.ooni.io/": dns_nxdomain_error [recovered]
	panic: client.Do failed: Post "https://wcth.ooni.io/": dns_nxdomain_error

goroutine 19 [running]:
testing.tRunner.func1.2(0xc40ac0, 0xc000064020)
	/opt/hostedtoolcache/go/1.16.2/x64/src/testing/testing.go:1144 +0x49f
testing.tRunner.func1(0xc00008d080)
	/opt/hostedtoolcache/go/1.16.2/x64/src/testing/testing.go:1147 +0x695
panic(0xc40ac0, 0xc000064020)
	/opt/hostedtoolcache/go/1.16.2/x64/src/runtime/panic.go:971 +0x499
github.com/ooni/probe-cli/v3/internal/engine/runtimex.PanicOnError(...)
	/home/runner/work/probe-cli/probe-cli/internal/engine/runtimex/runtimex.go:10
github.com/ooni/probe-cli/v3/internal/cmd/oohelper.main()
	/home/runner/work/probe-cli/probe-cli/internal/cmd/oohelper/oohelper.go:44 +0x868
github.com/ooni/probe-cli/v3/internal/cmd/oohelper.TestSmoke(0xc00008d080)
	/home/runner/work/probe-cli/probe-cli/internal/cmd/oohelper/oohelper_test.go:7 +0x7b
testing.tRunner(0xc00008d080, 0xd3c790)
	/opt/hostedtoolcache/go/1.16.2/x64/src/testing/testing.go:1194 +0x203
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.16.2/x64/src/testing/testing.go:1239 +0x5d8
```

See https://github.com/ooni/probe-cli/pull/256/checks?check_run_id=2112332477#step:5:94.

Cannot reproduce locally. I wonder if this issue is related to some rules set up by jafar tests?

**Comment by bassosimone** [comment]
So, this is not related by anything done by Jafar. In fact, the Jafar codebases does not reference `wcth.ooni.io`.

**Comment by bassosimone** [comment]
This is the only recurrent error blocking https://github.com/ooni/probe/issues/1369 :thinking:

**Comment by bassosimone** [comment]
Here's a verbose trace:

```
2021/04/01 16:59:58 debug resolve www.example.com...
2021/04/01 17:00:00 debug resolve www.example.com... ([93.184.216.34], <nil>) in 1.595358882s
2021/04/01 17:00:00 debug out: {"http_request":"http://www.example.com","http_request_headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Language":["en-US;q=0.8,en;q=0.5"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"]},"tcp_connect":["93.184.216.34:80"]}
2021/04/01 17:00:00 debug > POST https://wcth.ooni.io/
2021/04/01 17:00:00 debug > User-Agent: oohelper/3.9.0 ooniprobe-engine/3.9.0
2021/04/01 17:00:00 debug > Content-Type: application/json
2021/04/01 17:00:00 debug > Host: wcth.ooni.io     
2021/04/01 17:00:00 debug >                        
2021/04/01 17:00:00 debug resolve wcth.ooni.io...  
2021/04/01 17:00:00 debug resolve wcth.ooni.io... ([], dns_nxdomain_error) in 1.026807ms
2021/04/01 17:00:00 debug < dns_nxdomain_error     
--- FAIL: TestSmoke (1.60s)
panic: client.Do failed: Post "https://wcth.ooni.io/": dns_nxdomain_error [recovered]
	panic: client.Do failed: Post "https://wcth.ooni.io/": dns_nxdomain_error

goroutine 19 [running]:
testing.tRunner.func1.2(0xc4f320, 0xc0002f7360)
	/opt/hostedtoolcache/go/1.16.2/x64/src/testing/testing.go:1144 +0x49f
testing.tRunner.func1(0xc000087080)
	/opt/hostedtoolcache/go/1.16.2/x64/src/testing/testing.go:1147 +0x695
panic(0xc4f320, 0xc0002f7360)
	/opt/hostedtoolcache/go/1.16.2/x64/src/runtime/panic.go:971 +0x499
github.com/ooni/probe-cli/v3/internal/engine/runtimex.PanicOnError(...)
	/home/runner/work/probe-cli/probe-cli/internal/engine/runtimex/runtimex.go:10
github.com/ooni/probe-cli/v3/internal/cmd/oohelper.main()
	/home/runner/work/probe-cli/probe-cli/internal/cmd/oohelper/oohelper.go:44 +0x868
github.com/ooni/probe-cli/v3/internal/cmd/oohelper.TestSmoke(0xc000087080)
	/home/runner/work/probe-cli/probe-cli/internal/cmd/oohelper/oohelper_test.go:8 +0xaa
testing.tRunner(0xc000087080, 0xd4ca90)
	/opt/hostedtoolcache/go/1.16.2/x64/src/testing/testing.go:1194 +0x203
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.16.2/x64/src/testing/testing.go:1239 +0x5d8
FAIL	github.com/ooni/probe-cli/v3/internal/cmd/oohelper	1.706s
```

From https://github.com/ooni/probe-cli/pull/282/checks?check_run_id=2247983946

**Comment by bassosimone** [comment]
I've committed a workaround for this weird issue!
