### ISSUE TITLE
oonimkall: crash posting on closed channel

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1438]
```
panic: send on closed channel
goroutine 118 [running]:
 github.com/ooni/probe-cli/v3/pkg/oonimkall/internal/tasks.(*EventEmitter).Emit(...)
 	/Users/runner/work/probe-cli/probe-cli/pkg/oonimkall/internal/tasks/eventemitter.go:39
 github.com/ooni/probe-cli/v3/pkg/oonimkall/internal/tasks.(*ChanLogger).Debug(...)
 	/Users/runner/work/probe-cli/probe-cli/pkg/oonimkall/internal/tasks/chanlogger.go:19
 github.com/ooni/probe-cli/v3/pkg/oonimkall/internal/tasks.(*ChanLogger).Debugf(0x400012a300, 0x7f8ce444d4, 0x3b, 0x4000180850, 0x7, 0x7)
 	/Users/runner/work/probe-cli/probe-cli/pkg/oonimkall/internal/tasks/chanlogger.go:29 +0x160
 github.com/ooni/probe-cli/v3/internal/engine/netx/dialer.LoggingTLSHandshaker.Handshake(0x7f8ddd1e78, 0x40001db890, 0x7f8edfcd38, 0x400012a300, 0x7f8dde1998, 0x40002ea900, 0x7f8dde8ea0, 0x40004d3020, 0x40004ca900, 0x7f8dd76b60, ...)
 	/Users/runner/work/probe-cli/probe-cli/internal/engine/netx/dialer/logging.go:48 +0x444
 github.com/ooni/probe-cli/v3/internal/engine/netx/dialer.TLSDialer.DialTLSContext(0x4000c83c80, 0x7f8ddd1fb8, 0x40001db880, 0x7f8edf2110, 0x4000d4c960, 0x7f8dde1998, 0x40002ea900, 0x7f8ce1cf7e, 0x3, 0x4000434570, ...)
 	/Users/runner/work/probe-cli/probe-cli/internal/engine/netx/dialer/tls.go:135 +0x130
 net/http.(*Transport).customDialTLS(0x4000394b40, 0x7f8dde1998, 0x40002ea900, 0x7f8ce1cf7e, 0x3, 0x4000434570, 0x11, 0x0, 0x0, 0x0, ...)
 	/Users/runner/hostedtoolcache/go/1.16.2/x64/src/net/http/transport.go:1310 +0x58
 net/http.(*Transport).dialConn(0x4000394b40, 0x7f8dde1998, 0x40002ea900, 0x0, 0x4000498580, 0x5, 0x4000434570, 0x11, 0x0, 0x400044c480, ...)
 	/Users/runner/hostedtoolcache/go/1.16.2/x64/src/net/http/transport.go:1576 +0x22c
 net/http.(*Transport).dialConnFor(0x4000394b40, 0x4000444420)
 	/Users/runner/hostedtoolcache/go/1.16.2/x64/src/net/http/transport.go:1442 +0x68
 created by net/http.(*Transport).queueForDial
 	/Users/runner/hostedtoolcache/go/1.16.2/x64/src/net/http/transport.go:1423 +0x130
```

**Comment by bassosimone** [comment]
It seems the problem is that we should use two channels. One for posting messages to the main thread which is never closed and another channel to signal that the background thread is now gone. Messages posted on the channel, also, need to have some sort of timeout so that _late_ messages do not cause the background thread to block forever. It may also be that the pattern we are using could be further improved to avoid this kind of problems. While continuing to triage this issue, I will spend more time thinking about it.

**Comment by bassosimone** [comment]
Will continue this work in the next Sprint.
