### ISSUE TITLE
android: crash when opening the test details

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1442]
A kind OONI Probe user reported to us that their app is now crashing when they attempt to open the test results. They say the problem manifests itself when you tap on the test details. Re-installing the app didn't help. Wiping the data didn't help.

After you tap on the test details there is a freeze after which you get the message that the app stopped working.

We should investigate this problem and see whether perhaps we have any stack-trace or crash report that could help us diagnose this very annoying problem with the Android app.

**Comment by cyBerta** [comment]
I've been running into that issue as well. Here's a log with the stack trace

```
2021-04-10 18:11:01.040 12388-12388/org.openobservatory.ooniprobe.dev W/y.ooniprobe.de: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (greylist-max-q,core-platform-api, reflection, denied)
2021-04-10 18:11:01.041 12388-12388/org.openobservatory.ooniprobe.dev D/AndroidRuntime: Shutting down VM
2021-04-10 18:11:01.042 12388-12388/org.openobservatory.ooniprobe.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openobservatory.ooniprobe.dev, PID: 12388
    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:944)
        at org.openobservatory.ooniprobe.common.Application.getOkHttpClient(Application.java:75)
        at org.openobservatory.ooniprobe.common.Application.getApiClientWithUrl(Application.java:85)
        at org.openobservatory.ooniprobe.common.Application.getApiClient(Application.java:92)
        at org.openobservatory.ooniprobe.activity.AbstractActivity.getApiClient(AbstractActivity.java:27)
        at org.openobservatory.ooniprobe.activity.MeasurementDetailActivity.onCreate(MeasurementDetailActivity.java:207)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
        at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:370)
        at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:204)
        at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:178)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:179)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:944) 
        at org.openobservatory.ooniprobe.common.Application.getOkHttpClient(Application.java:75) 
        at org.openobservatory.ooniprobe.common.Application.getApiClientWithUrl(Application.java:85) 
        at org.openobservatory.ooniprobe.common.Application.getApiClient(Application.java:92) 
        at org.openobservatory.ooniprobe.activity.AbstractActivity.getApiClient(AbstractActivity.java:27) 
        at org.openobservatory.ooniprobe.activity.MeasurementDetailActivity.onCreate(MeasurementDetailActivity.java:207) 
        at android.app.Activity.performCreate(Activity.java:8000) 
        at android.app.Activity.performCreate(Activity.java:7984) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by cyBerta** [comment]
updating retrofit and the logging-interceptor fixes the issue for me:
```
	implementation 'com.squareup.retrofit2:retrofit:2.9.0'
	implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
	implementation 'com.squareup.okhttp3:logging-interceptor:4.9.1'
```

**Comment by bassosimone** [comment]
Thank you, @cyBerta!
