### ISSUE TITLE
qa/fbmessenger: frequent failures

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1594]
I see qa/fbmessenger frequently failing when run on GHA. Example:

```
2020-09-02T14:33:07.9718986Z    • jafar command line: [./jafar, -main-command, ./QA/minioonilike.py ./miniooni -n -o '/tmp/fbmessenger.jsonl' --home /tmp facebook_messenger, -main-user, nobody, -tag, fbmessenger_tcp_blocked_for_all, -iptables-reset-ip, stun.fbsbx.com, -iptables-reset-ip, b-api.facebook.com, -iptables-reset-ip, b-graph.facebook.com, -iptables-reset-ip, edge-mqtt.facebook.com, -iptables-reset-ip, external.xx.fbcdn.net, -iptables-reset-ip, scontent.xx.fbcdn.net, -iptables-reset-ip, star.c10r.facebook.com]
2020-09-02T14:33:07.9719631Z    • jafar tag: fbmessenger_tcp_blocked_for_all
2020-09-02T14:33:08.3880577Z    • exec: sudo iptables -D OUTPUT -j JAFAR_OUTPUT
2020-09-02T14:33:08.3910394Z iptables v1.8.4 (legacy): Couldn't load target `JAFAR_OUTPUT':No such file or directory
2020-09-02T14:33:08.3910616Z 
2020-09-02T14:33:08.3911070Z Try `iptables -h' or 'iptables --help' for more information.
2020-09-02T14:33:08.3914925Z    • exec result: exit status 2
2020-09-02T14:33:08.3915367Z    • exec: sudo iptables -D INPUT -j JAFAR_INPUT
2020-09-02T14:33:08.3939521Z iptables v1.8.4 (legacy): Couldn't load target `JAFAR_INPUT':No such file or directory
2020-09-02T14:33:08.3939669Z 
2020-09-02T14:33:08.3940108Z Try `iptables -h' or 'iptables --help' for more information.
2020-09-02T14:33:08.3943815Z    • exec result: exit status 2
2020-09-02T14:33:08.3944667Z    • exec: sudo iptables -t nat -D OUTPUT -j JAFAR_NAT_OUTPUT
2020-09-02T14:33:08.3968613Z iptables v1.8.4 (legacy): Couldn't load target `JAFAR_NAT_OUTPUT':No such file or directory
2020-09-02T14:33:08.3968728Z 
2020-09-02T14:33:08.3969113Z Try `iptables -h' or 'iptables --help' for more information.
2020-09-02T14:33:08.3974326Z    • exec result: exit status 2
2020-09-02T14:33:08.3974706Z    • exec: sudo iptables -F JAFAR_INPUT
2020-09-02T14:33:08.4000188Z iptables: No chain/target/match by that name.
2020-09-02T14:33:08.4009885Z    • exec result: exit status 1
2020-09-02T14:33:08.4010414Z    • exec: sudo iptables -X JAFAR_INPUT
2020-09-02T14:33:08.4030236Z iptables: No chain/target/match by that name.
2020-09-02T14:33:08.4036550Z    • exec result: exit status 1
2020-09-02T14:33:08.4037077Z    • exec: sudo iptables -F JAFAR_OUTPUT
2020-09-02T14:33:08.4053997Z iptables: No chain/target/match by that name.
2020-09-02T14:33:08.4062056Z    • exec result: exit status 1
2020-09-02T14:33:08.4062626Z    • exec: sudo iptables -X JAFAR_OUTPUT
2020-09-02T14:33:08.4079210Z iptables: No chain/target/match by that name.
2020-09-02T14:33:08.4083169Z    • exec result: exit status 1
2020-09-02T14:33:08.4084927Z    • exec: sudo iptables -t nat -F JAFAR_NAT_OUTPUT
2020-09-02T14:33:08.4107003Z iptables: No chain/target/match by that name.
2020-09-02T14:33:08.4111134Z    • exec result: exit status 1
2020-09-02T14:33:08.4111551Z    • exec: sudo iptables -t nat -X JAFAR_NAT_OUTPUT
2020-09-02T14:33:09.3806770Z iptables: No chain/target/match by that name.
2020-09-02T14:33:09.3808494Z    • exec result: exit status 1
2020-09-02T14:33:09.3809544Z    • exec: sudo iptables -N JAFAR_INPUT
2020-09-02T14:33:09.3810287Z    • exec result: <nil>       
2020-09-02T14:33:09.3810761Z    • exec: sudo iptables -N JAFAR_OUTPUT
2020-09-02T14:33:09.3811389Z    • exec result: <nil>       
2020-09-02T14:33:09.3812380Z    • exec: sudo iptables -t nat -N JAFAR_NAT_OUTPUT
2020-09-02T14:33:09.3812945Z    • exec result: <nil>       
2020-09-02T14:33:09.3813616Z    • exec: sudo iptables -I OUTPUT -j JAFAR_OUTPUT
2020-09-02T14:33:09.3815041Z    • exec result: <nil>       
2020-09-02T14:33:09.3816045Z    • exec: sudo iptables -I INPUT -j JAFAR_INPUT
2020-09-02T14:33:09.3816475Z    • exec result: <nil>       
2020-09-02T14:33:09.3817088Z    • exec: sudo iptables -t nat -I OUTPUT -j JAFAR_NAT_OUTPUT
2020-09-02T14:33:09.3817390Z    • exec result: <nil>       
2020-09-02T14:33:09.3817805Z    • exec: sudo iptables -A JAFAR_OUTPUT --proto tcp -d stun.fbsbx.com -j REJECT --reject-with tcp-reset
2020-09-02T14:33:09.3818104Z    • exec result: <nil>       
2020-09-02T14:33:09.3818518Z    • exec: sudo iptables -A JAFAR_OUTPUT --proto tcp -d b-api.facebook.com -j REJECT --reject-with tcp-reset
2020-09-02T14:33:09.3818812Z    • exec result: <nil>       
2020-09-02T14:33:09.3819212Z    • exec: sudo iptables -A JAFAR_OUTPUT --proto tcp -d b-graph.facebook.com -j REJECT --reject-with tcp-reset
2020-09-02T14:33:09.3819504Z    • exec result: <nil>       
2020-09-02T14:33:09.3819920Z    • exec: sudo iptables -A JAFAR_OUTPUT --proto tcp -d edge-mqtt.facebook.com -j REJECT --reject-with tcp-reset
2020-09-02T14:33:09.3820227Z    • exec result: <nil>       
2020-09-02T14:33:09.3820640Z    • exec: sudo iptables -A JAFAR_OUTPUT --proto tcp -d external.xx.fbcdn.net -j REJECT --reject-with tcp-reset
2020-09-02T14:33:09.3821138Z    • exec result: <nil>       
2020-09-02T14:33:09.3821632Z    • exec: sudo iptables -A JAFAR_OUTPUT --proto tcp -d scontent.xx.fbcdn.net -j REJECT --reject-with tcp-reset
2020-09-02T14:33:09.3821926Z    • exec result: <nil>       
2020-09-02T14:33:09.3822344Z    • exec: sudo iptables -A JAFAR_OUTPUT --proto tcp -d star.c10r.facebook.com -j REJECT --reject-with tcp-reset
2020-09-02T14:33:09.3822615Z    • exec result: <nil>       
2020-09-02T14:33:09.3823759Z    • exec: sudo -u nobody -- ./QA/minioonilike.py ./miniooni -n -o /tmp/fbmessenger.jsonl --home /tmp facebook_messenger
2020-09-02T14:33:09.3824023Z [      0.000272] <info> miniooni state directory: /tmp/.miniooni
2020-09-02T14:33:09.3824273Z [      0.000519] <info> miniooni temporary directory: /tmp/ooniengine110258530
2020-09-02T14:33:09.3824849Z [      0.000540] <info> Looking up OONI backends; please be patient...
2020-09-02T14:33:10.0116183Z [      1.426502] <info> session: using probe services: {Address:https://ps2.ooni.io Type:https Front:}
2020-09-02T14:33:10.0117048Z [      1.426517] <info> Looking up your location; please be patient...
2020-09-02T14:33:10.7087573Z [      2.123440] <info> - IP: 52.170.39.148
2020-09-02T14:33:10.7089721Z [      2.123467] <info> - country: US
2020-09-02T14:33:10.7090126Z [      2.123473] <info> - network: Microsoft Corporation (AS8075)
2020-09-02T14:33:10.7090726Z [      2.123477] <info> - resolver's IP: 40.71.8.98
2020-09-02T14:33:10.7091284Z [      2.123500] <info> - resolver's network: Microsoft Corporation (AS8075)
2020-09-02T14:33:10.7124390Z [      2.127519] <info> [ 14.3%] facebook_messenger: measure tcpconnect://star.c10r.facebook.com:443: <nil>
2020-09-02T14:33:10.7188529Z [      2.133451] <info> [ 28.6%] facebook_messenger: measure tcpconnect://b-api.facebook.com:443: connection_refused
2020-09-02T14:33:10.7189435Z [      2.133773] <info> [ 42.9%] facebook_messenger: measure tcpconnect://external.xx.fbcdn.net:443: connection_refused
2020-09-02T14:33:10.7247391Z [      2.139827] <info> [ 57.1%] facebook_messenger: measure dnslookup://stun.fbsbx.com: <nil>
2020-09-02T14:33:10.7286119Z [      2.143695] <info> [ 71.4%] facebook_messenger: measure tcpconnect://b-graph.facebook.com:443: connection_refused
2020-09-02T14:33:10.7288946Z [      2.144046] <info> [ 85.7%] facebook_messenger: measure tcpconnect://edge-mqtt.facebook.com:443: connection_refused
2020-09-02T14:33:10.7342115Z [      2.149261] <info> [100.0%] facebook_messenger: measure tcpconnect://scontent.xx.fbcdn.net:443: <nil>
2020-09-02T14:33:10.7347931Z [      2.149957] <info> saving measurement to disk
2020-09-02T14:33:10.7352301Z [      2.150374] <info> experiment: recv   0  byte, sent   0  byte
2020-09-02T14:33:10.7360810Z [      2.151188] <info> whole session: recv   4 kbyte, sent   3 kbyte
2020-09-02T14:33:10.7374251Z minioonilike.py: ./miniooni --home /tmp -n -o /tmp/fbmessenger.jsonl facebook_messenger
2020-09-02T14:33:10.7442149Z    • exec result: <nil>       
2020-09-02T14:33:10.7442527Z    • exec: sudo iptables -D OUTPUT -j JAFAR_OUTPUT
2020-09-02T14:33:10.7472776Z    • exec result: <nil>       
2020-09-02T14:33:10.7473223Z    • exec: sudo iptables -D INPUT -j JAFAR_INPUT
2020-09-02T14:33:10.7504218Z    • exec result: <nil>       
2020-09-02T14:33:10.7504646Z    • exec: sudo iptables -t nat -D OUTPUT -j JAFAR_NAT_OUTPUT
2020-09-02T14:33:10.7530576Z    • exec result: <nil>       
2020-09-02T14:33:10.7530978Z    • exec: sudo iptables -F JAFAR_INPUT
2020-09-02T14:33:10.7556817Z    • exec result: <nil>       
2020-09-02T14:33:10.7557786Z    • exec: sudo iptables -X JAFAR_INPUT
2020-09-02T14:33:10.7592032Z    • exec result: <nil>       
2020-09-02T14:33:10.7592431Z    • exec: sudo iptables -F JAFAR_OUTPUT
2020-09-02T14:33:10.7615113Z    • exec result: <nil>       
2020-09-02T14:33:10.7615540Z    • exec: sudo iptables -X JAFAR_OUTPUT
2020-09-02T14:33:10.7644678Z    • exec result: <nil>       
2020-09-02T14:33:10.7645120Z    • exec: sudo iptables -t nat -F JAFAR_NAT_OUTPUT
2020-09-02T14:33:10.7669484Z    • exec result: <nil>       
2020-09-02T14:33:10.7670113Z    • exec: sudo iptables -t nat -X JAFAR_NAT_OUTPUT
2020-09-02T14:33:10.7696544Z    • exec result: <nil>       
2020-09-02T14:33:10.7725132Z Traceback (most recent call last):
2020-09-02T14:33:10.7725429Z   File "./QA/fbmessenger.py", line 286, in <module>
2020-09-02T14:33:10.7725938Z     main()
2020-09-02T14:33:10.7726110Z   File "./QA/fbmessenger.py", line 281, in main
2020-09-02T14:33:10.7726260Z     test(ooni_exe, outfile)
2020-09-02T14:33:10.7726451Z   File "./QA/fbmessenger.py", line 206, in fbmessenger_tcp_blocked_for_all
2020-09-02T14:33:10.7726653Z     assert tk["facebook_scontent_cdn_reachable"] == False
2020-09-02T14:33:10.7726789Z AssertionError
2020-09-02T14:33:10.9684155Z ##[error]Process completed with exit code 1.
2020-09-02T14:33:10.9753346Z Post job cleanup.
2020-09-02T14:33:11.0977171Z [command]/usr/bin/git version
2020-09-02T14:33:11.1052724Z git version 2.28.0
2020-09-02T14:33:11.1102044Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-09-02T14:33:11.1150099Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-09-02T14:33:11.1443768Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-09-02T14:33:11.1471454Z http.https://github.com/.extraheader
2020-09-02T14:33:11.1489589Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-09-02T14:33:11.1522501Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-09-02T14:33:11.1867051Z Cleaning up orphan processes
```

See https://github.com/ooni/probe-engine/runs/1062037329

**Comment by bassosimone** [comment]
In https://github.com/ooni/probe-cli/pull/938, I have determined that we can afford to keep QA checks for Web Connectivity only, since the maintainer burden caused by QA was quite a bit. Better be realistic.
