### ISSUE TITLE
wcth: compare old and new test helpers

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1707]
This issue is about fetching all the URLs in all the test lists with both helpers and comparing the results. We want to understand in which cases the new test helper differs from the old test helper and why.

**Comment by bassosimone** [comment]
Here's a status update. In late July I run a first pass comparison of the whole content of the test lists between the old and the new test helper.

To this end, I used the code at https://github.com/ooni/wcthcheck.

The codename of this first comparison is `config-0`. Running the `./compare` tool of the above mentioning repository using `config-0`, we get:

**Comment by bassosimone** [comment]
Written status update. We can now move to Sprint 49.

**Comment by bassosimone** [comment]
# Making sure the errors are the same

To approach this problem, we'll basically try to map errors from `netxlite` to strings emitted by the old TH. To understand which strings are emitted by the old TH, we need to read the source code.

The code that matters is at https://github.com/ooni/backend/blob/6ec4fda5b18/oonib/testhelpers/http_helpers.py. There are three `try...except` of interest: one of DNS, one for TCP connect, and one for HTTP.

I have implemented a diff (soon to be committed along with tests) that maps netxlite errors to TH error strings. Let us see whether this diff is working okay for us by running some manual tests.

## DNS checks

### Result in case of NXDOMAIN

Let us cause NXDOMAIN using jafar like:

```bash
./jafar -iptables-hijack-dns-to 127.0.0.1:53 -dns-proxy-block example.com
```

Let us now call the old and the new THs running locally using `http://example.com` as input.

Here's the old TH's output:

```JSON
{
    "tcp_connect": {
        "93.184.216.34:80": {
            "status": true,
            "failure": null
        },
        "[2606:2800:220:1:248:1893:25c8:1946]:80": {
            "status": false,
            "failure": "invalid_socket"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "dns_lookup_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": "dns_name_error",
        "addrs": []
    }
}
```

And here is the new TH result:

```JSON
{
    "tcp_connect": {
        "93.184.216.34:80": {
            "status": true,
            "failure": null
        },
        "[2606:2800:220:1:248:1893:25c8:1946]:80": {
            "status": false,
            "failure": "connect_error"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "dns_lookup_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": "dns_name_error",
        "addrs": []
    }
}
```

### Result in case of DNS timeout

```
./jafar -iptables-hijack-dns-to 127.0.0.1:53 -dns-proxy-ignore example.com
```

Old TH:

```JSON
{
    "tcp_connect": {
        "93.184.216.34:80": {
            "status": true,
            "failure": null
        },
        "[2606:2800:220:1:248:1893:25c8:1946]:80": {
            "status": false,
            "failure": "invalid_socket"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "dns_lookup_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": "unknown_error",
        "addrs": []
    }
}
```

New TH:

```JSON
{
    "tcp_connect": {
        "93.184.216.34:80": {
            "status": true,
            "failure": null
        },
        "[2606:2800:220:1:248:1893:25c8:1946]:80": {
            "status": false,
            "failure": "connect_error"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "generic_timeout_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": "unknown_error",
        "addrs": []
    }
}
```

## TCP

Here we're going to use `http://dns.google` and  its `8.8.8.8:443` and `8.8.4.4:443` endpoints.

### Connection refused

```bash
./jafar -iptables-reset-ip 8.8.8.8 -iptables-reset-ip 8.8.4.4
```

Old TH:

```JSON
{
    "tcp_connect": {
        "8.8.4.4:80": {
            "status": false,
            "failure": "connection_refused_error"
        },
        "8.8.8.8:80": {
            "status": false,
            "failure": "connection_refused_error"
        },
        "[2001:4860:4860::8844]:80": {
            "status": false,
            "failure": "invalid_socket"
        },
        "[2001:4860:4860::8888]:80": {
            "status": false,
            "failure": "invalid_socket"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "connection_refused_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": null,
        "addrs": [
            "8.8.8.8",
            "8.8.4.4"
        ]
    }
}
```

New TH:

```JSON
{
    "tcp_connect": {
        "8.8.4.4:80": {
            "status": false,
            "failure": "connection_refused_error"
        },
        "8.8.8.8:80": {
            "status": false,
            "failure": "connection_refused_error"
        },
        "[2001:4860:4860::8844]:80": {
            "status": false,
            "failure": "connect_error"
        },
        "[2001:4860:4860::8888]:80": {
            "status": false,
            "failure": "connect_error"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "connection_refused_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": null,
        "addrs": [
            "8.8.8.8",
            "8.8.4.4",
            "2001:4860:4860::8888",
            "2001:4860:4860::8844"
        ]
    }
}
```

### Connect timed out

```bash
```

Old TH:

```JSON
{
    "tcp_connect": {
        "8.8.4.4:80": {
            "status": false,
            "failure": "generic_timeout_error"
        },
        "8.8.8.8:80": {
            "status": false,
            "failure": "generic_timeout_error"
        },
        "[2001:4860:4860::8844]:80": {
            "status": false,
            "failure": "invalid_socket"
        },
        "[2001:4860:4860::8888]:80": {
            "status": false,
            "failure": "invalid_socket"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "generic_timeout_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": "unknown_error",
        "addrs": []
    }
}
```

New TH:

```JSON
{
    "tcp_connect": {
        "8.8.4.4:80": {
            "status": false,
            "failure": "generic_timeout_error"
        },
        "8.8.8.8:80": {
            "status": false,
            "failure": "generic_timeout_error"
        },
        "[2001:4860:4860::8844]:80": {
            "status": false,
            "failure": "connect_error"
        },
        "[2001:4860:4860::8888]:80": {
            "status": false,
            "failure": "connect_error"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "generic_timeout_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": "unknown_error",
        "addrs": []
    }
}
```

## TLS

We continue to use dns.google but we try to filter the TLS handshake.

### Connection reset

```bash
./jafar -iptables-reset-keyword google
```

The old TH resets the connection and we therefore see the following error in the `oohelper` client:

```
panic: client.Do failed: Post "http://192.168.1.6:9020/": connection_reset

goroutine 1 [running]:
github.com/ooni/probe-cli/v3/internal/runtimex.PanicOnError(...)
	/Users/sbs/src/github.com/bassosimone/ooniwcthcheck/probe-cli/internal/runtimex/runtimex.go:10
main.wcth()
	/Users/sbs/src/github.com/bassosimone/ooniwcthcheck/probe-cli/internal/cmd/oohelper/oohelper.go:92 +0x1b8
main.main()
	/Users/sbs/src/github.com/bassosimone/ooniwcthcheck/probe-cli/internal/cmd/oohelper/oohelper.go:60 +0x2b0
```

The new TH returns:

```JSON
{
    "tcp_connect": {
        "8.8.4.4:443": {
            "status": true,
            "failure": null
        },
        "8.8.8.8:443": {
            "status": true,
            "failure": null
        },
        "[2001:4860:4860::8844]:443": {
            "status": false,
            "failure": "connect_error"
        },
        "[2001:4860:4860::8888]:443": {
            "status": false,
            "failure": "connect_error"
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "unknown_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": null,
        "addrs": [
            "8.8.8.8",
            "8.8.4.4",
            "2001:4860:4860::8844",
            "2001:4860:4860::8888"
        ]
    }
}
```

### Handshake timeout

It seems we cannot easily implement this test case for Jafar at the moment. (Maybe circle back later?)

### Invalid certificate

Here we're using `https://expired.badssl.com` as the test case without any Jafar usage.

Old TH:

```JSON
{
    "tcp_connect": {
        "104.154.89.105:443": {
            "status": true,
            "failure": null
        }
    },
    "http_request": {
        "body_length": 494,
        "failure": null,
        "title": "expired.badssl.com",
        "headers": {
            "Cache-Control": "no-store",
            "Content-Type": "text/html",
            "Date": "Wed, 13 Oct 2021 13:00:58 GMT",
            "ETag": "W/\"6164d5db-1ee\"",
            "Last-Modified": "Tue, 12 Oct 2021 00:24:59 GMT",
            "Server": "nginx/1.10.3 (Ubuntu)"
        },
        "status_code": 200
    },
    "dns": {
        "failure": null,
        "addrs": [
            "104.154.89.105"
        ]
    }
}
```

New TH:

```JSON
{
    "tcp_connect": {
        "104.154.89.105:443": {
            "status": true,
            "failure": null
        }
    },
    "http_request": {
        "body_length": -1,
        "failure": "unknown_error",
        "title": "",
        "headers": {},
        "status_code": -1
    },
    "dns": {
        "failure": null,
        "addrs": [
            "104.154.89.105"
        ]
    }
}
```

## HTTP

We basically have already tested all the handled cases above.

## Conclusion

The new TH matches the old TH in most cases. There are some differences. Most probes are new probes nowadays and they do not match with old TH strings except for "dns_name_error", which we're currently handling.

**Comment by bassosimone** [comment]
So, what remains now is to submit the code that tries to match errors along with some unit tests. Then, there is also need to continue running the tool for a more broad set of inputs and circle back and figure out what other differences we have.

**Comment by bassosimone** [comment]
I also started looking into HTTP headers. I found more cases in which the set is disjoint, so I added more headers as exception, but then I also measured in which cases both sets ended up being empty. This is not looking good:

```
  "http_headers/failure/new": 883,
  "http_headers/failure/old": 5141,
  "http_headers/match/no_header_left": 9378,
  "http_headers/match/same_set": 9060,
  "http_headers/mismatch/set_diff": 925,
  "http_headers/total": 19363,
```

There are two issues here: (1) we have many HTTP failures for which we probably need to retry and (2) the more I add exception headers the more I increase the `no_header_left`. That is: `set_diff` and `no_header_left` cannot both be optimised at the same time. So perhaps the approach I am using for headers here is wrong. I think we should _just_ eliminate the headers that the probe would not consider without adding further exceptions. Doing that now.

**Comment by bassosimone** [comment]
Regarding the status code, after correcting to avoid noise caused by failures, here's what I get:

```
  "http_status_code/failure/new": 885,
  "http_status_code/failure/old": 5142,
  "http_status_code/match": 19030,
  "http_status_code/mismatch": 343,
  "http_status_code/total": 25400,
```

It may be worth taking a look into the mismatch cases and see whether there's anything fundamental here.
