### ISSUE TITLE
ci: panic: unexpected key: log

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1785]
**Describe the bug**
We've been seeing intermittent CI build errors. For example: https://github.com/ooni/probe-cli/runs/3720114001.

**To Reproduce**
Run the CI and eventually it happens (one in 2-4 runs).

**Expected behavior**

**Screenshots**
Not really a screenshot, but the failed output is:

```
ok  	github.com/ooni/probe-cli/v3/pkg/oonimkall	19.737s	coverage: 72.7% of statements
2021/09/27 12:29:59 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
panic: unexpected key: log

goroutine 28 [running]:
github.com/ooni/probe-cli/v3/pkg/oonimkall/internal/tasks.TestRunnerMaybeLookupLocationFailure.func1()
	/home/runner/work/probe-cli/probe-cli/pkg/oonimkall/internal/tasks/runner_internal_test.go:57 +0x32a
created by github.com/ooni/probe-cli/v3/pkg/oonimkall/internal/tasks.TestRunnerMaybeLookupLocationFailure
	/home/runner/work/probe-cli/probe-cli/pkg/oonimkall/internal/tasks/runner_internal_test.go:43 +0x2f9
```

**System information (please complete the following information):**
GitHub actions Linux based runner.

**Additional context**
It seems we're now emitting logs we previously did not emit.

**Comment by bassosimone** [comment]
Since https://github.com/ooni/probe-cli/pull/629, there are no more integration tests that panic in `oonimkall`. Hence we can close this issue. The original problem causing the failures does not exist anymore.
