### ISSUE TITLE
android: RunTestService.task: app crash 

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1916]
User provided stack trace:

```
java.lang.NullPointerException: Attempt to read from field 'org.openobservatory.ooniprobe.test.TestAsyncTask org.openobservatory.ooniprobe.common.service.RunTestService.task' on a null object reference
 at org.openobservatory.ooniprobe.fragment.ProgressFragment$TestRunBroadRequestReceiver.onReceive(ProgressFragment.java:146)
 at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
 at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
 at android.os.Handler.dispatchMessage(Unknown Source:21)
 at android.os.Looper.loop(Unknown Source:139)
 at android.app.ActivityThread.main(Unknown Source:65)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
 at com.android.internal.os.ZygoteInit.main(Unknown Source:338)
```

**Comment by lorenzoPrimi** [comment]
This has been already fixed in https://github.com/ooni/probe-android/commit/145e7154efe098bfcf9ab314f38c2676ef827dbf
