### ISSUE TITLE
desktop-macos: auto updater fails to restart the application

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1974]
I was on OONI Probe 3.5.2 and once the auto updater downloaded the latest version (3.6.1) and tried to apply the update, it fails to restart with the following error:

```
[2022-01-17 13:19:35.406] [info]  New version 3.6.1 has been downloaded to /Users/art/Library/Application Support/Cache
s/ooniprobe-desktop-updater/pending/OONI-Probe-3.6.1-mac.zip
[2022-01-17 13:19:35.428] [info]  Update downloaded. Quitting and installing.
[2022-01-17 13:19:35.431] [warn]  Error: The command is disabled and cannot be executed
    at Server.<anonymous> (/Users/art/code/ooni/probe-desktop/dist/mac/OONI Probe.app/Contents/Resources/app.asar/node_
modules/electron-updater/out/MacUpdater.js:185:34)
    at Object.onceWrapper (events.js:312:28)
    at Server.emit (events.js:223:5)
    at Server.EventEmitter.emit (domain.js:475:20)
    at emitListeningNT (net.js:1340:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2022-01-17 13:19:35.432] [error] Error: Error: The command is disabled and cannot be executed
    at Server.<anonymous> (/Users/art/code/ooni/probe-desktop/dist/mac/OONI Probe.app/Contents/Resources/app.asar/node_
modules/electron-updater/out/MacUpdater.js:185:34)
    at Object.onceWrapper (events.js:312:28)
    at Server.emit (events.js:223:5)
    at Server.EventEmitter.emit (domain.js:475:20)
    at emitListeningNT (net.js:1340:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2022-01-17 13:19:35.432] [info]  Unable to check for updates. Please visit https://ooni.org/ to get the latest version.
```

When I manually restart the application, I can see that the update has in fact been applied.

This problem seems to be related to a bug with electron-builder: https://github.com/electron-userland/electron-builder/issues/5935 which was fixed starting from `22.11.10`, while we are still on `22.7.0`.

I think what we should do is upgrade to the latest version of electron-builder.

**Comment by ttomaszewski** [comment]
We're on `22.13.1` and still having this issue, but maybe itll work for you.

**Comment by hellais** [comment]
This is probably something we will not address in light of the multiplatform work. Closing.
