### ISSUE TITLE
engine: nil-pointer panic when experiment.Run fails

### ISSUE THREAD

**Issue by aanorbel** [ooni/probe#2173]
**Describe the bug**

Running circumvention tests on mobile fails when trying to run `tor` test.

**Logs**
```
D/TestAsyncTask: run next suite: circumvention test:tor
D/MK_EVENT: {"key":"status.queued","value":{}}
W/UNUSED_KEY: status.queued
D/MK_EVENT: {"key":"status.started","value":{}}
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"Looking up OONI backends... please, be patient"}}
D/TestAsyncTask: TestAsyncTask.RUN
D/TestAsyncTask: TestAsyncTask.PRG 100
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"sessionresolver: https://cloudflare-dns.com/dns-query... ok"}}
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"sessionresolver: https://dns.google/dns-query... ok"}}
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"session: using probe services: {Address:https://ps1.ooni.io Type:https Front:}"}}
D/MK_EVENT: {"key":"status.progress","value":{"message":"contacted bouncer","percentage":0.1}}
D/TestAsyncTask: TestAsyncTask.PRG 110
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"Looking up your location... please, be patient"}}
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"iplookup: using ubuntu"}}
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"sessionresolver: https://cloudflare-dns.com/dns-query... ok"}}
D/MK_EVENT: {"key":"status.progress","value":{"message":"geoip lookup","percentage":0.2}}
D/TestAsyncTask: TestAsyncTask.PRG 120
D/MK_EVENT: {"key":"status.progress","value":{"message":"resolver lookup","percentage":0.3}}
D/MK_EVENT: {"key":"status.geoip_lookup","value":{"probe_asn":"AS15964","probe_cc":"CM","probe_ip":"154.72.153.203","probe_network_name":"CAMEROON TELECOMMUNICATIONS NETWORK"}}
D/MK_EVENT: {"key":"status.resolver_lookup","value":{"resolver_asn":"AS15169","resolver_ip":"172.253.5.129","resolver_network_name":"Google LLC"}}
W/UNUSED_KEY: status.resolver_lookup
D/TestAsyncTask: TestAsyncTask.PRG 130
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"Opening report... please, be patient"}}
D/MK_EVENT: {"key":"status.progress","value":{"message":"open report","percentage":0.4}}
D/TestAsyncTask: TestAsyncTask.PRG 140
D/MK_EVENT: {"key":"status.report_create","value":{"report_id":"20220629T063720Z_tor_CM_15964_n1_fghZZoGW9jcHXSI4"}}
D/MK_EVENT: {"key":"log","value":{"log_level":"INFO","message":"Starting measurement with index 0"}}
D/MK_EVENT: {"key":"status.measurement_start","value":{"idx":0,"input":""}}
V/FlowLog: Executing query: SELECT COUNT(*) FROM `Result` WHERE (`id`=11) 
V/FlowLog: Executing query: SELECT COUNT(*) FROM `Network` WHERE (`id`=3) 
E/Go: panic: runtime error: invalid memory address or nil pointer dereference
E/Go: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x767188251e05]
E/Go: 
E/Go: goroutine 1504 [running]:
E/Go: github.com/ooni/probe-cli/v3/internal/model.(*Measurement).AddAnnotation(...)
E/Go: 	/home/runner/work/probe-cli/probe-cli/internal/model/measurement.go:134
E/Go: github.com/ooni/probe-cli/v3/internal/model.(*Measurement).AddAnnotations(0x0, 0x767188e95a30)
E/Go: 	/home/runner/work/probe-cli/probe-cli/internal/model/measurement.go:128 +0xa5
E/Go: github.com/ooni/probe-cli/v3/pkg/oonimkall.(*runnerForTask).Run(0xc0005f3fa0, {0x767188e959f8, 0xc000486a40})
E/Go: 	/home/runner/work/probe-cli/probe-cli/pkg/oonimkall/taskrunner.go:294 +0x1b8c
E/Go: github.com/ooni/probe-cli/v3/pkg/oonimkall.StartTask.func1()
E/Go: 	/home/runner/work/probe-cli/probe-cli/pkg/oonimkall/task.go:50 +0x16e
E/Go: created by github.com/ooni/probe-cli/v3/pkg/oonimkall.StartTask
E/Go: 	/home/runner/work/probe-cli/probe-cli/pkg/oonimkall/task.go:46 +0x1fa
    
    --------- beginning of crash
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27594 (Thread-12), pid 27501 (y.ooniprobe.dev)

```

**Comment by bassosimone** [comment]
We have to do the following:

1. fix the issue (easy);
2. write a regression test (also easy);
3. cherry-pick into release branch;
4. update dependencies;
5. release.

**Comment by bassosimone** [comment]
Fixed master with https://github.com/ooni/probe-cli/pull/821 and `release/3.15` with https://github.com/ooni/probe-cli/commit/072802764e5a7affc67ecd1445d76c214d5f9907
