### ISSUE TITLE
probe-desktop: fix broken integration tests on CI

### ISSUE THREAD

**Issue by hellais** [ooni/probe#2348]
Several integration tests currently fail. It's unclear at which point exactly they broke and what the root cause is.

Currently these are the stats on the integration tests:
```
Tests:       4 failed, 96 passed, 100 total
```

The failing ones are these:
```
● All network tests run successfully › IM test runs from start to finish

    waitUntilTextExists waitUntil condition timed out after 30000ms

      at node_modules/webdriverio/build/commands/browser/waitUntil.js:24:19
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Browser.waitUntilTextExists (node_modules/@wdio/utils/build/shim.js:63:29)

  ● All network tests run successfully › Middleboxes test runs from start to finish

    waitUntilTextExists waitUntil condition timed out after 30000ms

      at node_modules/webdriverio/build/commands/browser/waitUntil.js:24:19
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Browser.waitUntilTextExists (node_modules/@wdio/utils/build/shim.js:63:29)

  ● All network tests run successfully › Performance test runs from start to finish

    waitUntilTextExists waitUntil condition timed out after 30000ms

      at node_modules/webdriverio/build/commands/browser/waitUntil.js:24:19
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Browser.waitUntilTextExists (node_modules/@wdio/utils/build/shim.js:63:29)

  ● All network tests run successfully › Experimental test runs from start to finish

    waitUntilTextExists waitUntil condition timed out after 30000ms

      at node_modules/webdriverio/build/commands/browser/waitUntil.js:24:19
      at Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:63:29)
      at Browser.waitUntilTextExists (node_modules/@wdio/utils/build/shim.js:63:29)
```

I tried reproducing the issue locally, but weren't able to.

OTOH, when I ran them locally the localization test failed:
```
 FAIL  test/localization.e2e.js (8.02 s)
  Localized version is displayed for supported languages
    ✕ Check if the app shows content in French (141 ms)
  Unsupported language (Malayalam) falls back to English
    ✓ Run button label in English (169 ms)

  ● Localized version is displayed for supported languages › Check if the app shows content in French

    expect(received).toMatch(expected)

    Expected substring: "Lancer"
    Received string:    "Run"

      21 |     const runButtonText = await app.utils.getText('button[data-testid=button-dashboard-run]')
      22 |
    > 23 |     expect(runButtonText).toMatch('Lancer')
         |                           ^
      24 |   })
      25 | })
      26 |

      at Object.<anonymous> (test/localization.e2e.js:23:27)
```

**Comment by hellais** [comment]
This is referring to an old version of the app. Closing.
