### ISSUE TITLE
android: log view crashes when using debug logs

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2508]
**Describe the bug**

The log view crashes when using debug logs.

**To Reproduce**

* Enable debug logs
* Run IM
* Open the logs view in advanced

**Expected behavior**

The view should show the logs. (I suspect we're allocating too much memory?)

**Screenshots**

N/A

**System information (please complete the following information):**

- Device: Pixel 4a
 - OS: Android 13
 - OONI Probe version: https://github.com/ooni/probe-android/commit/36b29ca15d590a35ee8423a7c84e1377b4eda33b and v3.8.3 installed from the play store (and using v3.17.5 as its engine)

**Additional context**

The following seems to be the reason why the app crashed (not sure whether this is an OOM):

```
07-21 14:24:33.576  8046  8046 D AndroidRuntime: Shutting down VM
07-21 14:24:33.576  8046  8046 E AndroidRuntime: FATAL EXCEPTION: main
07-21 14:24:33.576  8046  8046 E AndroidRuntime: Process: org.openobservatory.ooniprobe, PID: 8046
07-21 14:24:33.576  8046  8046 E AndroidRuntime: java.lang.IllegalArgumentException: No view found for id 0x7f0a0240 (org.openobservatory.ooniprobe:id/subContent) for fragment PreferenceFragment{44a1d57} (a77fcc95-856b-4513-be86-c9caf4f2f703 id=0x7f0a0240)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8366)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3666)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-21 14:24:33.576  8046  8046 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
07-21 14:24:33.587  1716  2906 E ActivityManager: App crashed on incremental package org.openobservatory.ooniprobe which is 100% loaded.
```

**Comment by bassosimone** [comment]
I think we need to do a bit more work on this issue. The following screenshot illustrates what my logs look like. Basically, the main problem is that DEBUG logs are for some reason not included in the logs view. See:

![photo1690194606](https://github.com/ooni/probe/assets/337298/cfbc11d9-99f1-41db-89fb-efb503e8df53)

Note that the messages are correctly labeled as DEBUG in the logcat, so it's not an engine issue:

<img width="1384" alt="Screenshot 2023-07-24 at 12 29 11" src="https://github.com/ooni/probe/assets/337298/d8c8cec9-30fe-4354-8ece-f6dd990f436b">

As such, I am reopening the issue.
