### ISSUE TITLE
android: crash with custom list

### ISSUE THREAD

**Issue by marek22k** [ooni/probe#2632]
**Describe the bug**

When opening a link from https://run.ooni.io/ OONI Probe crashes.

**To Reproduce**

Open the following link in the Firefox browser on Android and click on the "Run" button at "You already have the OONI Probe mobile app".

**Expected behavior**

Open OONI Probe and test the list.

**System information (please complete the following information):**

- Device: Samsung SM-G960F
 - OS: Android 13 iodeOS version 4.7-20231114-starlte
 - OONI Probe version: 3.8.4 from F-Droid

**Additional context**

Log from LogFox: 
[crash-org-openobservatory-ooniprobe-20_11-01-15-43_496.zip](https://github.com/ooni/probe/files/13405064/crash-org-openobservatory-ooniprobe-20_11-01-15-43_496.zip)

```
FATAL EXCEPTION: main
Process: org.openobservatory.ooniprobe, PID: 8923
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openobservatory.ooniprobe/org.openobservatory.ooniprobe.activity.OoniRunActivity}: java.lang.NumberFormatException: For input string: "undefined"
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NumberFormatException: For input string: "undefined"
	at java.lang.Integer.parseInt(Integer.java:747)
	at java.lang.Integer.valueOf(Integer.java:1078)
	at org.openobservatory.ooniprobe.domain.VersionCompare.compare(VersionCompare.java:33)
	at org.openobservatory.ooniprobe.activity.OoniRunActivity.loadScreen(OoniRunActivity.java:108)
	at org.openobservatory.ooniprobe.activity.OoniRunActivity.manageIntent(OoniRunActivity.java:86)
	at org.openobservatory.ooniprobe.activity.OoniRunActivity.onCreate(OoniRunActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:8348)
	at android.app.Activity.performCreate(Activity.java:8327)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1421)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more
```
Link:
```
https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Fwiki.dn42.us%2F%22%2C%22https%3A%2F%2Fdn42.eu%2F%22%2C%22https%3A%2F%2Fdn42.dev%2F%22%2C%22https%3A%2F%2Fdn42.tk%2F%22%2C%22https%3A%2F%2Fdn42.cc%2F%22%2C%22https%3A%2F%2Fdn42.wiki%2F%22%2C%22https%3A%2F%2Fdn42.de%2F%22%2C%22https%3A%2F%2Fdn42.us%2F%22%2C%22https%3A%2F%2Fdn42.lutoma.org%2F%22%2C%22https%3A%2F%2Fwww.chrismoos.com%2F%22%2C%22https%3A%2F%2Fdn42.potat0.cc%2F%22%2C%22https%3A%2F%2Fdn42.kskb.eu.org%2F%22%2C%22https%3A%2F%2Fdn42.kuu.moe%2F%22%2C%22https%3A%2F%2Fsgp.dn42.icez.net%2F%22%2C%22https%3A%2F%2Fnet.whojk.com%2F%22%2C%22https%3A%2F%2Fdn42.lare.cc%2F%22%2C%22https%3A%2F%2Fpeer.dn42.6700.cc%2F%22%2C%22https%3A%2F%2Fdn42.0011.de%2F%22%2C%22https%3A%2F%2Fdn42.g-load.eu%2F%22%2C%22https%3A%2F%2Futil.sour.is%2F%22%2C%22https%3A%2F%2Fpaste.dn42.us%2F%22%2C%22https%3A%2F%2Fraumzeitlabor.de%2F%22%2C%22https%3A%2F%2Finferior.network%2F%22%2C%22https%3A%2F%2Fspectre-net.de%2F%22%2C%22https%3A%2F%2Fwww.liuquanhao.com%2F%22%2C%22https%3A%2F%2Fnognu.de%2F%22%2C%22https%3A%2F%2Fwww.hax404.de%2F%22%2C%22https%3A%2F%2Fwww.huajitech.net%2F%22%2C%22https%3A%2F%2Fredxen.eu%2F%22%2C%22https%3A%2F%2Fziad87.net%2F%22%2C%22https%3A%2F%2Fdn42.bb-pgqm.com%2F%22%2C%22https%3A%2F%2Fwww.cdubs.tech%2F%22%2C%22https%3A%2F%2Fdn42.atolm.net%2F%22%2C%22https%3A%2F%2Fbrand-web.net%2F%22%2C%22http%3A%2F%2Fdn42.y525.gq%2Fen%22%2C%22https%3A%2F%2Fyukipedia.cf%2F%22%2C%22https%3A%2F%2Fhighdef.network%2F%22%2C%22https%3A%2F%2Fdn42.scoopta.ninja%2F%22%2C%22https%3A%2F%2Fopen-desk.org%2F%22%2C%22https%3A%2F%2Fnicholas.wang%2F%22%2C%22https%3A%2F%2Fblog.benjojo.co.uk%2F%22%2C%22https%3A%2F%2Fwww.ljjserver.cn%2Fdn42%2F%22%2C%22https%3A%2F%2Ffamfo.xyz%2F%22%2C%22https%3A%2F%2Flemonsh.moe%2F%22%2C%22https%3A%2F%2Fdn42.canidae.systems%2F%22%2C%22https%3A%2F%2Fwww.morik.it%2F%22%2C%22https%3A%2F%2Fwww.koala.gq%2F%22%2C%22https%3A%2F%2Fdn42.h-k.sk%2F%22%2C%22https%3A%2F%2Fdn42.ca.melusfer.us%2Findex.html%22%2C%22https%3A%2F%2Fwww.tchekda.fr%2F%22%2C%22https%3A%2F%2Fpotat0.cc%2F%22%2C%22https%3A%2F%2Fdn42.kskb.eu.org%2F%22%2C%22https%3A%2F%2F5trubel.de%2F%22%2C%22https%3A%2F%2Flilynet.work%2F%22%2C%22http%3A%2F%2Fwww.freertr.org%2F%22%2C%22https%3A%2F%2Fdn42.keuin.cc%2F%22%2C%22https%3A%2F%2Fpebkac.gr%2F%22%2C%22https%3A%2F%2Fwww.zai.ge%2F%22%2C%22https%3A%2F%2Fdn42.est-it.de%2F%22%2C%22https%3A%2F%2Fmaraun.de%2F%22%2C%22https%3A%2F%2Fdn42.munsternet.eu%2F%22%2C%22https%3A%2F%2Fnadeen.lk%2F%22%2C%22https%3A%2F%2Flantian.pub%2F%22%2C%22https%3A%2F%2Fwww.androw.eu%2F%22%2C%22https%3A%2F%2Fchaox.ro%2F%22%2C%22https%3A%2F%2Fdn42.burble.com%2F%22%2C%22https%3A%2F%2Fmiaotony.xyz%2F%22%2C%22https%3A%2F%2Fnet.whojk.com%2F%22%2C%22https%3A%2F%2Fblog.uvokchee.de%2F%22%2C%22https%3A%2F%2Fmaglab.space%2Fde%2F%22%2C%22https%3A%2F%2Feki.moe%2F%22%2C%22https%3A%2F%2Fjlxip.net%2F%22%2C%22https%3A%2F%2Fdn42.mathinfo.xyz%2F%22%2C%22https%3A%2F%2Fyuuta.moe%2F%22%2C%22https%3A%2F%2Fwww.6700.cc%2F%22%2C%22https%3A%2F%2Funknownts.com%2F%22%2C%22https%3A%2F%2Ftheresa.cafe%2F%22%2C%22https%3A%2F%2Fjerryxiao.cc%2F%22%2C%22https%3A%2F%2F186526.xyz%2F%22%2C%22https%3A%2F%2Fdn42.cooo.cool%2F%23%2Fhome%22%2C%22https%3A%2F%2Fblog.sherpherd.top%2Fdn42.html%22%2C%22https%3A%2F%2Fffm.freifunk.net%2F%22%2C%22https%3A%2F%2Ffreifunk-3laendereck.net%2F%22%2C%22https%3A%2F%2Ffulda.freifunk.net%2F%22%2C%22https%3A%2F%2Fwww.neocloud.tw%2F%22%2C%22https%3A%2F%2Fneovax.neocloud.tw%2F%22%2C%22https%3A%2F%2Fbyeob.de%2F%22%2C%22https%3A%2F%2Fcrxn.de%2F%22%2C%22https%3A%2F%2Fdeavmi.assigned.network%2F%22%2C%22https%3A%2F%2Fsour.is%2F%22%2C%22https%3A%2F%2F04d.co%2F%22%2C%22https%3A%2F%2Fdn42.napshome.net%2F%22%2C%22https%3A%2F%2Fnapshome.net%2F%22%2C%22https%3A%2F%2Famcforum.wiki%2F%22%2C%22https%3A%2F%2Fdn42.pebkac.gr%2F%22%2C%22https%3A%2F%2Fest-it.de%2F%22%2C%22https%3A%2F%2Fdn42.saru.moe%2F%22%2C%22https%3A%2F%2Fsaru.moe%2F%22%2C%22https%3A%2F%2Fwhojk.com%2F%22%2C%22https%3A%2F%2Fdn42.6700.cc%2F%22%2C%22https%3A%2F%2Fprevarinite.net%2F%22%2C%22https%3A%2F%2Fstrexp.net%2F%22%2C%22https%3A%2F%2Fmk16.de%2F%22%2C%22https%3A%2F%2Fgit.dn42.dev%2F%22%2C%22https%3A%2F%2Fgithub.com%2Frouter-city%2Frouter-city%22%2C%22https%3A%2F%2Fgithub.com%2FNeoCloud%2FNeoNetwork%22%2C%22https%3A%2F%2Fgithub.com%2Flukes%2FISO-3166-Countries-with-Regional-Codes%2Ftree%2Fmaster%22%2C%22https%3A%2F%2Fgithub.com%2FExa-Networks%2Fexabgp%22%2C%22https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FDn42%22%2C%22https%3A%2F%2Fgroups.io%2Fg%2Fdn42%2F%22%2C%22https%3A%2F%2Fbird.network.cz%2F%22%2C%22https%3A%2F%2Ffrrouting.org%2F%22%2C%22https%3A%2F%2Fwww.wireguard.com%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fneocturne%2Ffastd%22%2C%22https%3A%2F%2Ffastd.readthedocs.io%2F%22%2C%22https%3A%2F%2Fopenvpn.net%2F%22%2C%22https%3A%2F%2Fstrongswan.org%2F%22%2C%22https%3A%2F%2Ftinc-vpn.org%2F%22%2C%22https%3A%2F%2Fopenbgpd.org%2F%22%2C%22https%3A%2F%2Fui.com%2F%22%2C%22https%3A%2F%2Fwww.cisco.com%2F%22%2C%22https%3A%2F%2Fmikrotik.com%2F%22%2C%22https%3A%2F%2Fvyos.net%2F%22%2C%22https%3A%2F%2Fvyos.io%2F%22%2C%22https%3A%2F%2Fopenwrt.org%2F%22%2C%22https%3A%2F%2Fwww.hackint.org%2F%22%2C%22https%3A%2F%2Flg.sour.is%2F%22%2C%22https%3A%2F%2Flg.04d.co%2F%22%2C%22https%3A%2F%2Flg.dn42.napshome.net%2F%22%2C%22https%3A%2F%2Flg.amcforum.wiki%2F%22%2C%22https%3A%2F%2Flg.highdef.network%2F%22%2C%22https%3A%2F%2Flg42.tchekda.fr%2F%22%2C%22https%3A%2F%2Flg.sfsarfe.com%2F%22%2C%22https%3A%2F%2Flg.dn42.pebkac.gr%2F%22%2C%22https%3A%2F%2Flg.dn42.est-it.de%2F%22%2C%22https%3A%2F%2Flg.dn42.munsternet.eu%2F%22%2C%22https%3A%2F%2Flg.dn42.saru.moe%2F%22%2C%22https%3A%2F%2Flg.chaox.ro%2F%22%2C%22https%3A%2F%2Flg.whojk.com%2F%22%2C%22http%3A%2F%2Flg.eb.dn42%2F%22%2C%22https%3A%2F%2Flg.eastbnd.com%2F%22%2C%22https%3A%2F%2Flg.doxz.net%2F%22%2C%22https%3A%2F%2Flg.lare.cc%2F%22%2C%22https%3A%2F%2Flg.dn42.6700.cc%2F%22%2C%22https%3A%2F%2Fheimdall.prevarinite.net%2F%22%2C%22https%3A%2F%2Fbgp42.strexp.net%2F%22%2C%22https%3A%2F%2Fmap.kuu.moe%2F%22%2C%22https%3A%2F%2Fmap.meson.cc%2F%22%2C%22https%3A%2F%2Froutegraphs.highdef.network%2F%22%2C%22https%3A%2F%2Fdn42-bgplookup.mk16.de%2F%22%5D%7D&mv=1.2.0
```

When I click on "Open in app" in Firefox, the following message appears:
![error](https://github.com/ooni/probe/assets/46723399/d66ab48d-423d-404b-99f7-c6e3b122bad6)

Furthermore, it seems that Firefox truncates the URL to the following:
```
https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Fwiki.dn42.us%2F%22%2C%22https%3A%2F%2Fdn42.eu%2F%22%2C%22https%3A%2F%2Fdn42.dev%2F%22%2C%22https%3A%2F%2Fdn42.tk%2F%22%2C%22https%3A%2F%2Fdn42.cc%2F%22%2C%22https%3A%2F%2Fdn42.wiki%2F%22%2C%22https%3A%2F%2Fdn42.de%2F%22%2C%22https%3A%2F%2Fdn42.us%2F%22%2C%22https%3A%2F%2Fdn42.lutoma.org%2F%22%2C%22https%3A%2F%2Fwww.chrismoos.com%2F%22%2C%22https%3A%2F%2Fdn42.potat0.cc%2F%22%2C%22https%3A%2F%2Fdn42.kskb.eu.org%2F%22%2C%22https%3A%2F%2Fdn42.kuu.moe%2F%22%2C%22https%3A%2F%2Fsgp.dn42.icez.net%2F%22%2C%22https%3A%2F%2Fnet.whojk.com%2F%22%2C%22https%3A%2F%2Fdn42.lare.cc%2F%22%2C%22https%3A%2F%2Fpeer.dn42.6700.cc%2F%22%2C%22https%3A%2F%2Fdn42.0011.de%2F%22%2C%22https%3A%2F%2Fdn42.g-load.eu%2F%22%2C%22https%3A%2F%2Futil.sour.is%2F%22%2C%22https%3A%2F%2Fpaste.dn42.us%2F%22%2C%22https%3A%2F%2Fraumzeitlabor.de%2F%22%2C%22https%3A%2F%2Finferior.network%2F%22%2C%22https%3A%2F%2Fspectre-net.de%2F%22%2C%22https%3A%2F%2Fwww.liuquanhao.com%2F%22%2C%22https%3A%2F%2Fnognu.de%2F%22%2C%22https%3A%2F%2Fwww.hax404.de%2F%22%2C%22https%3A%2F%2Fwww.huajitech.net%2F%22%2C%22https%3A%2F%2Fredxen.eu%2F%22%2C%22https%3A%2F%2Fziad87.net%2F%22%2C%22https%3A%2F%2Fdn42.bb-pgqm.com%2F%22%2C%22https%3A%2F%2Fwww.cdubs.tech%2F%22%2C%22https%3A%2F%2Fdn42.atolm.net%2F%22%2C%22https%3A%2F%2Fbrand-web.net%2F%22%2C%22http%3A%2F%2Fdn42.y525.gq%2Fen%22%2C%22https%3A%2F%2Fyukipedia.cf%2F%22%2C%22https%3A%2F%2Fhighdef.network%2F%22%2C%22https%3A%2F%2Fdn42.scoopta.ninja%2F%22%2C%22https%3A%2F%2Fopen-desk.org%2F%22%2C%22https%3A%2F%2Fnicholas.wang%2F%22%2C%22https%3A%2F%2Fblog.benjojo.co.uk%2F%22%2C%22https%3A%2F%2Fwww.ljjserver.cn%2Fdn42%2F%22%2C%22https%3A%2F%2Ffamfo.xyz%2F%22%2C%22https%3A%2F%2Flemonsh.moe%2F%22%2C%22https%3A%2F%2Fdn42.canidae.systems%2F%22%2C%22https%3A%2F%2Fwww.morik.it%2F%22%2C%22https%3A%2F%2Fwww.koala.gq%2F%22%2C%22https%3A%2F%2Fdn42.h-k.sk%2F%22%2C%22https%3A%2F%2Fdn42.ca.melusfer.us%2Findex.html%22%2C%22https%3A%2F%2Fwww.tchekda.fr%2F%22%2C%22https%3A%2F%2Fpotat0.cc%2F%22%2C%22https%3A%2F%2Fdn42.kskb.eu.org%2F%22%2C%22https%3A%2F%2F5trubel.de%2F%22%2C%22https%3A%2F%2Flilynet.work%2F%22%2C%22http%3A%2F%2Fwww.freertr.org%2F%22%2C%22https%3A%2F%2Fdn42.keuin.cc%2F%22%2C%22https%3A%2F%2Fpebkac.gr%2F%22%2C%22https%3A%2F%2Fwww.zai.ge%2F%22%2C%22https%3A%2F%2Fdn42.est-it.de%2F%22%2C%22https%3A%2F%2Fmaraun.de%2F%22%2C%22https%3A%2F%2Fdn42.munsternet.eu%2F%22%2C%22https%3A%2F%2Fnadeen.lk%2F%22%2C%22https%3A%2F%2Flantian.pub%2F%22%2C%22https%3A%2F%2Fwww.androw.eu%2F%22%2C%22https%3A%2F%2Fchaox.ro%2F%22%2C%22https%3A%2F%2Fdn42.burble.com%2F%22%2C%22https%3A%2F%2Fmiaotony.xyz%2F%22%2C%22https%3A%2F%2Fnet.whojk.com%2F%22%2C%22https%3A%2F%2Fblog.uvokchee.de%2F%22%2C%22https%3A%2F%2Fmaglab.space%2Fde%2F%22%2C%22https%3A%2F%2Feki.moe%2F%22%2C%22https%3A%2F%2Fjlxip.net%2F%22%2C%22https%3A%2F%2Fdn42.mathinfo.xyz%2F%22%2C%22https%3A%2F%2Fyuuta.moe%2F%22%2C%22https%3A%2F%2Fwww.6700.cc%2F%22%2C%22https%3A%2F%2Funknownts.com%2F%22%2C%22https%3A%2F%2Ftheresa.cafe%2F%22%2C%22https%3A%2F%2Fjerryxiao.cc%2F%22%2C%22https%3A%2F%2F186526.xyz%2F%22%2C%22https%3A%2F%2Fdn42.cooo.cool%2F%23%2Fhome%22%2C%22https%3A%2F%2Fblog.sherpherd.top%2Fdn42.html%22%2C%22https%3A%2F%2Fffm.freifunk.net%2F%22%2C%22https%3A%2F%2Ffreifunk-3laendereck.net%2F%22%2C%22https%3A%2F%2Ffulda.freifunk.net%2F%22%2C%22https%3A%2F%2Fwww.neocloud.tw%2F%22%2C%22https%3A%2F%2Fneovax.neocloud.tw%2F%22%2C%22https%3A%2F%2Fbyeob.de%2F%22%2C%22https%3A%2F%2Fcrxn.de%2F%22%2C%22https%3A%2F%2Fdeavmi.assigned.network%2F%22%2C%22https%3A%2F%2Fsour.is%2F%22%2C%22https%3A%2F%2F04d.co%2F%22%2C%22https%3A%2F%2Fdn42.napshome.net%2F%22%2C%22https%3A%2F%2Fnapshome.net%2F%22%2C%22https%3A%2F%2Famcforum.wiki%2F%22%2C%22https%3A%2F%2Fdn42.pebkac.gr%2F%22%2C%22https%3A%2F%2Fest-it.de%2F%22%2C%22https%3A%2F%2Fdn42.saru.moe%2F%22%2C%22https%3A%2F%2Fsaru.moe%2F%22%2C%22https%3A%2F%2Fwhojk.com%2F%22%2C%22https%3A%2F%2Fdn42.6700.cc%2F%22%2C%22https%3A%2F%2Fprevarinite.net%2F%22%2C%22https%3A%2F%2Fstrexp.net%2F%22%2C%22https%3A%2F%2Fmk16.de%2F%22%2C%22https%3A%2F%2Fgit.dn42.dev%2F%22%2C%22https%3A%2F%2Fgithub.com%2Frouter-city%2Frouter-city%22%2C%22https%3A%2F%2Fgithub.com%2FNeoCloud%2FNeoNetwork%22%2C%22https%3A%2F%2Fgithub.com%2Flukes%2FISO-3166-Countries-with-Regional-Codes%2Ftree%2Fmaster%22%2C%22https%3A%2F%2Fgithub.com%2FExa-Networks%2Fexabgp%22%2C%22https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FDn42%22%2C%22https%3A%2F%2Fgroups.io%2Fg%2Fdn42%2F%22%2C%22https%3A%2F%2Fbird.network.cz%2F%22%2C%22https%3A%2F%2Ffrrouting.org%2F%22%2C%22https%3A%2F%2Fwww.wireguard.com%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fneocturne%2Ffastd%22%2C%22https%3A%2F%2Ffastd.readthedocs.io%2F%22%2C%22https%3A%2F%2Fopenvpn.net%2F%22%2C%22https%3A%2F%2Fstrongswan.org%2F%22%2C%22https%3A%2F%2Ftinc-vpn.org%2F%22%2C%22https%3A%2F%2Fopenbgpd.org%2F%22%2C%22https%3A%2F%2Fui.com%2F%22%2C%22https%3A%2F%2Fwww.cisco.com%2F%22%2C%22https%3A%2F%2Fmikrotik.com%2F%22%2C%22https%
```

Edit:
- not Firefox, but the Android clipboard seems to have truncated the URL.
- Clicking on a button or a link containing the URL works and opens the OONI app.

**Comment by aanorbel** [comment]
Hi @marek22k while testing the application to reproduce the error you reported, I wasn't able to make the application "Crash" as reported.

I was however able to confirm that copying the link and pasting on *Firefox*  breaks the link since the link exceeds the character limit that can be held in the clipboard.

Clicking on the link from an Email or any other method that doesn't truncate the contents of the contents, the app is launched with the appropriate data.

I would suggest you use the link from your email or any other application that doesn't truncate the contents.

Here is a spec for OONI Run V2 (https://github.com/ooni/spec/blob/master/backends/bk-005-ooni-run-v2.md) we are currently working on to fix all issues in the current OONI Run format.
