### ISSUE TITLE
Found Intent-Based Bug

### ISSUE THREAD

**Issue by Mai-hh** [ooni/probe#2782]
## Brief summary
Hi! I'm a security researcher currently working on a project in the area of Android app analysis. As a part of the work centered around Intents, I found a bug that resulted in crashes after analyzing logs/execution traces. Below are the relevant activities, traces, and adb commands that triggered the crashes.

This is a bug in an exposed component that another app can trigger. I can help provide more information as needed.

## org.openobservatory.ooniprobe/org.openobservatory.ooniprobe.activity.MeasurementDetailActivity

```
--------- beginning of crash
07-22 21:46:45.489  5207  5207 E AndroidRuntime: FATAL EXCEPTION: main
07-22 21:46:45.489  5207  5207 E AndroidRuntime: Process: org.openobservatory.ooniprobe, PID: 5207
07-22 21:46:45.489  5207  5207 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openobservatory.ooniprobe/org.openobservatory.ooniprobe.activity.MeasurementDetailActivity}: java.lang.NullPointerException: Attempt to read from field 'org.openobservatory.ooniprobe.model.database.Result org.openobservatory.ooniprobe.model.database.Measurement.result' on a null object reference in method 'void org.openobservatory.ooniprobe.activity.MeasurementDetailActivity.onCreate(android.os.Bundle)'
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'org.openobservatory.ooniprobe.model.database.Result org.openobservatory.ooniprobe.model.database.Measurement.result' on a null object reference in method 'void org.openobservatory.ooniprobe.activity.MeasurementDetailActivity.onCreate(android.os.Bundle)'
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at org.openobservatory.ooniprobe.activity.MeasurementDetailActivity.onCreate(MeasurementDetailActivity.java:70)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8305)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8284)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
07-22 21:46:45.489  5207  5207 E AndroidRuntime: 	... 12 more
```

adb command that triggers it:
```
#!/bin/bash

adb shell su 0 am start -n "org.openobservatory.ooniprobe/org.openobservatory.ooniprobe.activity.PreferenceActivity" --ei org.openobservatory.ooniprobe.fragment.PreferenceFragment.PREF_RES_ID 2 --es androidx.preference.PreferenceFragmentCompat.PREFERENCE_ROOT o 
echo adb shell su 0 am start -n "org.openobservatory.ooniprobe/org.openobservatory.ooniprobe.activity.PreferenceActivity" --ei org.openobservatory.ooniprobe.fragment.PreferenceFragment.PREF_RES_ID 2 --es androidx.preference.PreferenceFragmentCompat.PREFERENCE_ROOT o 
sleep 3.0
adb shell am force-stop org.openobservatory.ooniprobe
sleep 2.0
```

**Comment by Mai-hh** [comment]
I have updated my original comment and issue title to reflect that this is a bug in an exposed component that another app can easily trigger using Intent.

**Comment by Lanius-collaris** [comment]
@jbonisteel Forcibly launched a activity with unexpected input to get a crash… It may be spam.

**Comment by Mai-hh** [comment]
> @jbonisteel Forcibly launched a activity with unexpected input to get a crash… It may be spam.

This activity is an exposed component that another app can easily trigger. This means that another app can also provide unexpected input to cause the same crash. I provided the adb command for ease of reproducibility

**Comment by Lanius-collaris** [comment]
https://github.com/ooni/probe-android/blob/90544b57252611acc3969858890d9ada4b696757/app/src/main/AndroidManifest.xml#L42-L46
No intent-filter. No `android:exported="true"`.

https://developer.android.google.cn/guide/topics/manifest/activity-element#exported

**Comment by Mai-hh** [comment]
Thank you very much for your reply. I believe I made some mistakes while testing your app. I am very sorry for the disturbance. I will close this issue.
