### ISSUE TITLE
failure in running dnscheck experiment

### ISSUE THREAD

**Issue by DecFox** [ooni/probe#2799]
**Describe the bug**

It seems that running `dnscheck` using `miniooni` fails with a panic indicating an error in the input.

**To Reproduce**

Run:
```
go build -v ./internal/cmd/miniooni
./miniooni dnscheck
```

**Expected behavior**

The experiment should run successfully and upload the measurement to the ooni collector.

**Output**

The run logs show a panic and a `richer-input` error:
```
panic: cannot run experiment: invalid richer input type

goroutine 1 [running]:
github.com/ooni/probe-cli/v3/internal/runtimex.PanicOnError(...)
        /Users/decfox/Projects/OONI/probe-cli/internal/runtimex/runtimex.go:66
main.runx({0x105a11670?, 0x107b13180?}, {0x105a1a830?, 0x1400055e140?}, {0x105458109?, 0x105a18b08?}, 0x1
4000468b70?, 0x0?, 0x14000a7fa38?)
        /Users/decfox/Projects/OONI/probe-cli/internal/cmd/miniooni/runx.go:31 +0x158
main.mainSingleIteration({0x105a18b08, 0x14000468b70}, {0x105458109, 0x8}, 0x140003da580)
        /Users/decfox/Projects/OONI/probe-cli/internal/cmd/miniooni/main.go:401 +0x45c
main.MainWithConfiguration({0x105458109, 0x8}, 0x140003da580)
        /Users/decfox/Projects/OONI/probe-cli/internal/cmd/miniooni/main.go:330 +0x288
main.registerAllExperiments.func1(0x1400014e900?, {0x107b13180?, 0x4?, 0x1054506a0?})
        /Users/decfox/Projects/OONI/probe-cli/internal/cmd/miniooni/main.go:249 +0x2c
github.com/spf13/cobra.(*Command).execute(0x140002c0c08, {0x107b13180, 0x0, 0x0})
        /Users/decfox/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14000126908)
        /Users/decfox/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/decfox/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /Users/decfox/Projects/OONI/probe-cli/internal/cmd/miniooni/main.go:196 +0x4f4
```

**Comment by DecFox** [comment]
Following `release v3.23`, we also see a drop in measurement count for the `dnscheck`. This indicates that the bug affects engine versions >= 3.23

**Comment by jbonisteel** [comment]
Should fix this issue: https://github.com/ooni/ooni.org/issues/1595
