### ISSUE TITLE
ooniprobe fails to run/install in all supported variants of Debian and Ubuntu

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#693]
Below a log of ooniprobe failed installations and runs in Debian Jessie, Ubuntu 14.04, 16.04 and 16.10 with possible workaround.

### Installing ooniprobe from deb.torproject.org repository.

`# cat /etc/*release`
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
```

`# find /etc/apt/ -name *.list -type f -exec cat {} +`
```
deb http://ftp.nl.debian.org/debian jessie main
deb http://security.debian.org/ jessie/updates main
deb http://deb.torproject.org/torproject.org jessie main
```
`# apt-cache policy ooniprobe`
```
ooniprobe:
  Installed: 2.0.2-1~tpo8+1
  Candidate: 2.0.2-1~tpo8+1
  Version table:
 *** 2.0.2-1~tpo8+1 0
        500 http://deb.torproject.org/torproject.org/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
```
`# ooniprobe --version`
```
Traceback (most recent call last):
  File "/usr/bin/ooniprobe", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyOpenSSL>=0.15.1
```

### Workaround

Using jessie-backports to install a newest version of python-openssl:
`apt-get install -t jessie-backports python-openssl`

Install (downgrade) python-txtorcon version from stable repository to resolve:
```
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (txsocksx 0.0.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('txsocksx>=1.13.0'), set(['txtorcon']))
```
`apt-get install python-txtorcon=0.11.0-1`

### Installing ooniprobe from deb.torproject.org repository.

`# cat /etc/*release`
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
```

`# find /etc/apt/ -name *.list -type f -exec cat {} +`
```
deb http://nl.archive.ubuntu.com/ubuntu trusty main universe
deb http://security.ubuntu.com/ubuntu trusty-updates main
deb http://deb.torproject.org/torproject.org trusty main
```

`# apt-cache policy ooniprobe`
```
ooniprobe:
  Installed: 2.0.2-1~bpo+ubuntu14.04+1
  Candidate: 2.0.2-1~bpo+ubuntu14.04+1
  Version table:
 *** 2.0.2-1~bpo+ubuntu14.04+1 0
        500 http://deb.torproject.org/torproject.org/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

`# ooniprobe --version`
```
Traceback (most recent call last):
  File "/usr/bin/ooniprobe", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: geoip
```
Installing the python-geoip package from trusty-backports (version 1.3.2-1~14.04.1ubuntu1)
 resolves this issues but still a newer version of python-openssl (pyOpenSSL>=0.15.1) is
 needed that is not available on trusty to resolve the following issue:

`# ooniprobe -s`
```
Traceback (most recent call last):
  File "/usr/bin/ooniprobe", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyOpenSSL>=0.15.1
```

### Installing ooniprobe from deb.torproject.org repository.

`# cat /etc/*release`
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

`# find /etc/apt/ -name *.list -type f -exec cat {} +`
```
deb http://nl.archive.ubuntu.com/ubuntu xenial main
deb http://security.ubuntu.com/ubuntu xenial-updates main
deb http://deb.torproject.org/torproject.org xenial main
```

`# apt-cache policy ooniprobe`
```
ooniprobe:
  Installed: (none)
  Candidate: 2.0.2-1~tpo+ubuntu16.04+1
  Version table:
     2.0.2-1~tpo+ubuntu16.04+1 500
        500 http://deb.torproject.org/torproject.org xenial/main amd64 Packages
```

`# apt-get install ooniprobe`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ooniprobe : Depends: python-geoip but it is not installable
             Depends: python-scapy but it is not installable
             Depends: python-txsocksx but it is not installable
             Depends: python-txtorcon but it is not going to be installed
             Recommends: python-dumbnet but it is not installable
             Recommends: python-pypcap but it is not installable
E: Unable to correct problems, you have held broken packages.
```
### Workaround

Adding the universe repository and install ooniprobe

Remove the conflicting ooniprobe config file `/etc/ooniprobe.conf` to solve issue:

`ooniprobe manipulation/http_invalid_request_line`

```
Starting Tor
[!] You must set properly tor:socks_port in /var/lib/ooni/ooniprobe.conf.
[!] Failed to start tor
Unhandled Error
Traceback (most recent call last):
Failure: ooni.errors.ConfigFileIncoherent:

Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: ooni.errors.ConfigFileIncoherent:

Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: ooni.errors.ConfigFileIncoherent:

[!] Could not start the director
[!] Incoherent config file
```

## Ubuntu 16.10 (yaketty)

Same as in 16.04

### Workaround

Adding the universe repository and removing the configuration file `/etc/ooniprobe.conf`.

cc @irl

**Comment by irl** [comment]
Ok, so, list of tasks to fix:

[ ] Add python-openssl backport to deb.tpo jessie
[ ] Add python-geoip backport to deb.tpo trusty
[ ] Add python-openssl backport to deb.tpo trusty
[ ] Remove the ooniprobe.conf from:
 [ ] Debian unstable
 [ ] deb.tpo stretch
 [ ] deb.tpo jessie
 [ ] deb.tpo xenial
 [ ] deb.tpo yakkety
 [ ] deb.tpo trusty

@anadahz Does this sound like a complete list?

**Comment by hellais** [comment]
BTW we now have a CI that tries to install ooniprobe on all the supported platforms inside of docker containers running on travis: https://github.com/openobservatory/ooniprobe-ci

**Comment by anadahz** [comment]
@irl thanks, the list of tasks in https://github.com/TheTorProject/ooni-probe/issues/693#issuecomment-265135438 look good.

We need to ensure though a txtorcon package is being used that has no issues with the version comparison. A known good version of python-txtorcon is 0.11.0-1 since the deb.tpo package version (0.17.0-1) produces the following version conflict bug when running ooniprobe:
```
pkg_resources.ContextualVersionConflict: (txsocksx 0.0.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('txsocksx>=1.13.0'), set(['txtorcon']))
```

**Comment by hellais** [comment]
@irl since you are going to be rebuilding the packages anyways, it would be great if you could also bump to version 2.1.0 that was just recently released: https://pypi.python.org/packages/ea/31/f6ffff21b406b5c38b78f00b38897a48baae30eef0469089fb1330d86218/ooniprobe-2.1.0.tar.gz#md5=5981cf81cd2cdec8c2368194f5ded263

**Comment by irl** [comment]
2.1.0-1 removes /etc/ooniprobe.conf

```
 irl@orbiter  ~  ooniprobe manipulation/http_invalid_request_line
It looks like this is the first time you are running ooniprobe
Please take a minute to read through the informed consent documentation and understand what are the risks associated with running ooniprobe.
Press enter to continue...

Type "yes" if you are fully aware of the risks associated with using ooniprobe and you wish to proceed
> yes

Now help us configure some things!
Should we upload measurements to a collector? (Y/n)
Should we include your IP in measurements? (y/N)
Should we include your ASN (your network) in measurements? (Y/n)
Should we include your Country in measurements? (Y/n)
How would you like reports to be uploaded? (onion, https, cloudfront) https
ooniprobe is now initialized. You can begin using it!
Looking up your IP address via ubuntu
Found your IP via a GeoIP service
Moving /home/irl/.ooni/resources/CQRVl14K_Q1k2Dj5manifest.json to /home/irl/.ooni/resources/manifest.json
Moving /home/irl/.ooni/resources/citizenlab-test-lists/bgryvQQvzfOXgyqOglobal.csv to /home/irl/.ooni/resources/citizenlab-test-lists/global.csv
Moving /home/irl/.ooni/resources/tor-bridges/LXfXU7UVulIjygKgtor-bridges-ip-port.csv to /home/irl/.ooni/resources/tor-bridges/tor-bridges-ip-port.csv
Could not find input for country gb in /home/irl/.ooni/resources/citizenlab-test-lists/gb.csv
Looking up collector and test helpers with https://bouncer.ooni.io
Setting collector and test helpers for http_invalid_request_line
Creating report with OONIB Reporter. Please be patient.
This may take up to 1-2 minutes...
random_invalid_field_count: No manipulation detected.
random_invalid_version_number: No manipulation detected.
random_invalid_method: No manipulation detected.
random_big_request_method: No manipulation detected.
Report ID: 20161211T235842Z_AS786_VrkmDYtgiUZpLBC6w16xnHmCGb4McfZLqaNF58eYVDuBqtjxoJ
 irl@orbiter  ~  ooniprobe manipulation/http_invalid_request_line
Looking up your IP address via ubuntu
Found your IP via a GeoIP service
Looking up collector and test helpers with https://bouncer.ooni.io
Setting collector and test helpers for http_invalid_request_line
Creating report with OONIB Reporter. Please be patient.
This may take up to 1-2 minutes...
random_invalid_method: No manipulation detected.
random_invalid_field_count: No manipulation detected.
random_invalid_version_number: No manipulation detected.
random_big_request_method: No manipulation detected.
Report ID: 20161211T235856Z_AS786_JUyQRAbYImDE3JLz5pxKUQzUtb2inyxWDuPTEFcqqMvEf8E5ig

```

This is now uploaded to Debian unstable and deb.tpo unstable. More to come shortly...

**Comment by anadahz** [comment]
It seems that ooniprobe still fails to install in Ubuntu [trusty](https://travis-ci.org/OpenObservatory/ooniprobe-ci/jobs/211340426) and Debian [jessie](https://travis-ci.org/OpenObservatory/ooniprobe-ci/jobs/211340414).

@irl Do you need a hand on this to get the deb.tpo ooniprobe work in these versions too?

**Comment by irl** [comment]
It should work on Debian jessie using jessie backports. For Ubuntu trusty and Debian jessie I need to roll those versions back to the latest pre-2.0 version. It's not going to be possible to update those to 2.0+ due to missing dependencies.

**Comment by hellais** [comment]
> It should work on Debian jessie using jessie backports. 

I see jessie backports still has an old version of ooniprobe though: https://packages.debian.org/jessie-backports/ooniprobe

> For Ubuntu trusty and Debian jessie I need to roll those versions back to the latest pre-2.0 version. It's not going to be possible to update those to 2.0+ due to missing dependencies.

Which dependencies are missing? Can we backport the dependencies and add the to thetorproject debian repository?

**Comment by irl** [comment]
@hellais That's because of all the dependencies that would need to be backported. In theory we could add the dependencies to deb.tpo, but this would be a lot of packages as we don't just need the direct dependencies but also the indirect dependencies. I've had some discussions with Josh and weasel about packaging and we may want to be moving ooniprobe to a seperate suite where we can be less concerned about uploading large amounts of packages. The problem with having all these dependencies present on deb.tpo is that these new versions will be installed on every system that has deb.torproject.org in their apt sources (lots of people that just wanted Tor, not ooniprobe) and we could break lots of computers by doing non-backwards-compatible upgrades and break other software on their systems.

Another plan that I've been considering is shipping an OVA alongside the Debian packages. This would mean that we keep Debian packages up to date in every suite for as long as it's reasonable (for some value of reasonable) but on older suites you can always just run VirtualBox with the ooniprobe appliance which would have a Debian stable image (possibly with packages from backports if needed) that we would also enable unattended updates in. This is a similar model to the ArchiveTeam Warrior (http://archiveteam.org/index.php?title=ArchiveTeam_Warrior).

**Comment by hellais** [comment]
>  That's because of all the dependencies that would need to be backported. In theory we could add the dependencies to deb.tpo, but this would be a lot of packages as we don't just need the direct dependencies but also the indirect dependencies. I've had some discussions with Josh and weasel about packaging and we may want to be moving ooniprobe to a seperate suite where we can be less concerned about uploading large amounts of packages. The problem with having all these dependencies present on deb.tpo is that these new versions will be installed on every system that has deb.torproject.org in their apt sources (lots of people that just wanted Tor, not ooniprobe) and we could break lots of computers by doing non-backwards-compatible upgrades and break other software on their systems.

Yes I understand, this makes sense.
Do we want to at this point maybe setup our own apt repository (`deb.ooni.io`?) and host these over there?

> Another plan that I've been considering is shipping an OVA alongside the Debian packages. This would mean that we keep Debian packages up to date in every suite for as long as it's reasonable (for some value of reasonable) but on older suites you can always just run VirtualBox with the ooniprobe appliance which would have a Debian stable image (possibly with packages from backports if needed) that we would also enable unattended updates in. This is a similar model to the ArchiveTeam Warrior (http://archiveteam.org/index.php?title=ArchiveTeam_Warrior).

I have also have another possible suggestion. What about building a single executable that has inside all the dependencies needed (including python itself) with something like [pyinstaller](http://pythonhosted.org/PyInstaller/). That way we can ensure that the dependencies of ooniprobe do not end up polluting the rest of the system and avoid having to worry about breaking peoples system because the backported ooni dependency is incompatibile with some other software that depends on it.

**Comment by irl** [comment]
If we had a separate apt repo, I think I would be a lot happier to upload more dependencies as this would limit any damage to people that have chosen to run ooniprobe, not including people that only wanted Tor and would be upset that a thing they've never heard of has broken their system. We can discuss this in Amsterdam, but from you all I would need is a Debian stable VM and the DNS name pointed at it. I can then have debuilder and ubuilder upload packages to the repo.

pyinstaller looks like it's either going to be amazing or a nightmare of debugging. I wouldn't want to make Debian packages from anything it outputs, but perhaps that could be a way of distributing ooniprobe for some other platforms.

**Comment by bassosimone** [comment]
This issue is now historical. I am going to close it. There has been no activity for more than two years now and we're less than a month away from launching the new OONI 🤞
