### ISSUE TITLE
Unexpected token w in JSON at when running the middlebox test

### ISSUE THREAD

**Issue by xhdix** [ooni/probe#963]
![image](https://user-images.githubusercontent.com/12384263/69677166-605b2d80-10b3-11ea-93c7-7337e9338269.png)

```
[2019-11-27 01:35:02.722] [info] Runner: calling run middlebox
[2019-11-27 01:35:02.732] [info] running C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\bin\ooniprobe.exe [ '--batch', 'run', 'middlebox' ] { stdio: [ 'pipe', 'pipe', 'pipe' ],
  env:
   { OONI_HOME: 'C:\\Users\\username\\AppData\\Roaming\\OONI Probe\\ooni_home' } }
[2019-11-27 01:35:18.485] [error] failed to call JSON.parse 2019/11/27 01:35:18 error logging: json: unsupported value: +Inf SyntaxError: Unexpected token / in JSON at position 4
    at JSON.parse (<anonymous>)
    at DestroyableTransform.self.ooni.stderr.pipe.on.line (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\main\utils\ooni\ooniprobe.js:99:28)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:442:20)
    at addChunk (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\split2\index.js:52:10)
    at DestroyableTransform.transform [as _transform] (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\split2\index.js:33:5)
[2019-11-27 01:35:18.495] [error] failed to call JSON.parse 2019/11/27 01:35:18 error logging: json: unsupported value: +Inf SyntaxError: Unexpected token / in JSON at position 4
    at JSON.parse (<anonymous>)
    at DestroyableTransform.self.ooni.stderr.pipe.on.line (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\main\utils\ooni\ooniprobe.js:99:28)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:442:20)
    at addChunk (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\split2\index.js:52:10)
    at DestroyableTransform.transform [as _transform] (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\split2\index.js:33:5)
[2019-11-27 01:35:23.548] [error] failed to call JSON.parse terminate called after throwing an instance of 'nlohmann::detail::type_error' SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at DestroyableTransform.self.ooni.stderr.pipe.on.line (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\main\utils\ooni\ooniprobe.js:99:28)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:442:20)
    at addChunk (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\split2\index.js:52:10)
    at DestroyableTransform.transform [as _transform] (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\split2\index.js:33:5)
[2019-11-27 01:35:23.559] [error] failed to call JSON.parse   what():  [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xD9 SyntaxError: Unexpected token w in JSON at position 2
    at JSON.parse (<anonymous>)
    at DestroyableTransform.self.ooni.stderr.pipe.on.line (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\main\utils\ooni\ooniprobe.js:99:28)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:442:20)
    at addChunk (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at push (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\split2\index.js:52:10)
    at DestroyableTransform.transform [as _transform] (C:\Users\username\AppData\Local\Programs\ooniprobe-desktop\resources\app.asar\node_modules\split2\index.js:33:5)
[2019-11-27 01:35:23.597] [info] exited with code 3
```

```
Found backend option which is not mapped as a valid option. We will continue processing
Found no_geoip option which is not mapped as a valid option. We will continue processing
Found no_resolver_lookup option which is not mapped as a valid option. We will continue processing
Skipping bouncer
Your public IP address: *.*.*.*
Your country: IR
Your ISP identifier: AS****
Your ISP name: ****
Using helper: 37.218.241.93
Tampering detected: '' != 'GBYB / HTTP/1.1

'
Tampering detected: '' != 'X605W06OJTJR6VD44H6LXW8JIYWA3B3YG7IFA97SUIHAANU168N6TQBQUBPPZJ8NEAHY7965NH4L0KZV2MUAXESK0ODUS2VYFBBSQGZLPDBQAKBU4229X0EVDIAOMWPG291RBMK4CHAZRA3A220IPJQQNHLGRIEZ11YB8UIGAZ8Q2GVEWP9NNYYHZK3UOJSMR8ILVKX3TLJDQLMSLSWAV46W93TFF64O49QGSQNVX3GV3UI94YLSD9EI9MG0D2HFXSBQF75DSBX2AWH8OKY24M16NQMXJSTRYXLCBCQRB0MGXLBG3UPK6ZBMSDTXZZX72PGOE508HNQ9EGNVNY7DXZET2MQU35W1U82L1FQG8OU13TCT7DE7IPRU5RPJAAHZGE3322LFA5YB6GWY1P1NJQGGQH7C7X68ESWLVW20OT3NUZB6XDZ8L58ZBG7HO0U2BKYFZ16GU3KRVO3MZT7KUC38Y5K6OJHFIIC4FOLRZSGIF1P9AEXATTXXD74R2O164AL4DLIL9RTS607SFUTG4OBMYZ2R5A0I8O2K2FCSIOFMCK47XJLCOJOEG1RLR1S9HVW3EQV0F2EKXX0JAZ2P0OPWSFOOYBL7YMWSMCXTYLLVZP9H8UUCEW3R4XQ0KGJINLBM6OOSYK8SQR2GDKYTOA632EWAAOODV5XBOF14024K8EPPKOWP59ZQOHN1L7GAT4ZFRL7BIHLMTAONBJXGVZF2YBWQX55F7KU51GNQAQS9XHEESIOMP01A30295M9V80TBVIZGZ719023A217I3Z64P62NXG0V6FQIHLIJX75YNRHTOJFNL3HTJO7V3XIYBRDX1HWH0ZTI9XN6EBMVR2Z1QL83T7O5ZZJTPZCRG27NLHP11BR6TMECZ5CZOINMX32I54SG84SN5O5GJLV80YORLKUI3WLCX6SBSDRKVXLNL8CAFR1JZ1LZOE06UN19GTTKJCC5ERB1XHN5YRNLGRUGW4WA08UOJ71BAAW69A3BYC2H3WITQQPXCGSHLEOC / HTTP/1.1

'
Tampering detected: 'GET /vt/lyrX2Y' != 'GET / HTTP/X2Y'
Tampering detected: '' != 'GET cache_object://localhost/ HTTP/1.0

'
```

**Comment by hellais** [comment]
cc @bassosimone

**Comment by hellais** [comment]
@xhdix can you try updating to the latest OONI Probe desktop rc.4 and see if the bug persists? It would be super helpful if you could also check if the auto-update on windows works as expected.

You will have to do a hard reset as we have changed the layout of files on disk and measurement generated with rc.3 will not be accessible.

**Comment by xhdix** [comment]
>can you try updating to the latest OONI Probe desktop rc.4 and see if the bug persists? 

I see no problem.
Thanks!

> It would be super helpful if you could also check if the auto-update on windows works as expected.

Sorry. I was not aware of this request and installed it with the exe file.
I'll test this and let you know.
